### ISSUE TITLE
comments continue duplicated on live

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#102]
# How to reproduce
use comments.service-mock and scroll to bottom

**Comment by danconte72** [comment]
On comments mock service, update search function to consider lastItem parameter, or it will load all of comments duplicated

**Comment by danconte72** [comment]
> The sort() method sorts the elements of an array in place and returns the array. The sort is not necessarily stable. The default sort order is according to string Unicode code points. [(font 1)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) [(font 2)](https://medium.com/@fsufitch/is-javascript-array-sort-stable-46b90822543f)

**Comment by danconte72** [comment]
To keep mock works through different browsers, comment.published must be unique
