### ISSUE TITLE
Migrate to Ionic Storage (from localStorage) for local save of Auth data

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#111]

**Comment by danconte72** [comment]
Ionic Storage official [docs](https://ionicframework.com/docs/storage/)

**Comment by danconte72** [comment]
the main change is: 
- with Ionic storage all calls are promises

**Comment by danconte72** [comment]
- To allow start an Observable without value I changed from BehaviorSubject to Subject;
- There is no ngOnInit on [services](https://angular.io/tutorial/toh-pt4);
  - When call hasToken? 
[changes](https://github.com/meumobi/ion-employee/commit/eeedfbd4190dacf763ae2a465d4b6a46fe27652c)
