### ISSUE TITLE
FIX: e2e error, No element found using locator: By(css selector, page-settings) 

### ISSUE THREAD

**Issue by danconte72** [meumobi/infomobi#121]
Occurs after on refactor: move auth data to ionic storage
https://travis-ci.org/meumobi/ion-employee/builds/408075454

**Comment by vdias38** [comment]
> It tests using default services (not-mock); 

=> it’s normal e2e test to use default service

**Comment by danconte72** [comment]
- It tests using default services (not-mock); => it’s normal e2e test to use default service
- On new authDataPersistence service isLoggedSubject initiate without a value, the test only pass when isLoggedSubject starts false and set LoginPage as rootPage;
- It demands a rootPage before  authDataPersistence set some value on isLoggedSubject;
- Should rewrite the test to check login page
