### ISSUE TITLE
Feat: edit profile from “my account” link on sidemenu

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#136]
link is only visible by current user to edit its own profile

**Comment by danconte72** [comment]
- Create User-form Page and add on side;
- Create form based on dev-ams-report;
- User picture upload - component;

**Comment by danconte72** [comment]
- On create UserProfile before login, firstName, lastName and email are able to edit;
- After user login, meumobi data overwrite this field;
- On update this fields cannot be updated;
