### ISSUE TITLE
FIX: after logout I continue to be allowed to access on home

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#139]
I've logged out but my auth data remains on local db

![infomobi__improve_employee_experience](https://user-images.githubusercontent.com/9011612/43634885-64049a62-9705-11e8-9642-3c4725270e65.png)

**Comment by danconte72** [comment]
- I could not reproduce the error on Chrome/Safari

**Comment by vdias38** [comment]
How to reproduce
1. I logout, check authData is deleted on local db
2. call url with /#/home
3. the home page open, should redirect to login if none authData saved

**Comment by vdias38** [comment]
The app.component is not re-loaded if we update the url, it's home access is not forbidden.
Should add auth guards on each page to prevent access if AuthDataPersistence.state() return null
