### ISSUE TITLE
use device lang as default on bootstrap

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#144]
### Expected behaviour
If user has no profile saved/loaded on local should use [Platform.lang()](https://ionicframework.com/docs/api/platform/Platform/#lang) to set language (`translateService.use(...)`)

### Actual behaviour
On current version the default language is loaded until load of profile. But if browser.language is pt and default language is en, login page would use the wrong language.

### Expected responses
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've tested [Platform.lang()](https://ionicframework.com/docs/v3/api/platform/Platform/#lang) and
- On PT-BR macOS+chrome it returned EN;
- On EN iPhone it returned EN;
- On PT-BR iPhone it returned EN;

There is as Globalization ionic-native plugin who could handles language correctly https://ionicframework.com/docs/native/globalization#platforms with a web fallback

**Comment by danconte72** [comment]
Question:
- Will we keep preferred language on myAccount or move to preferences?
![image](https://user-images.githubusercontent.com/32454870/54536088-cc0ac980-496e-11e9-9d3c-fe4b50139de0.png)

  - If move to preferences we should save preferred language on ionicstorage;

**Comment by vdias38** [comment]
This issue doesn't concern user.language, but default language, so it's not related to preferences vs profile.
If Platform.lang not work should use another way to detect language, could be plugin for native App and anything else for PWA.

**Comment by danconte72** [comment]
how to get language on web [navigator.language](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language ) and it is [compatible](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language#Browser_compatibility) with all browsers that we support

I've tested 
- On PT-BR macOS+chrome it returned pt-BR;
- On EN iPhone NATIVE it returned en-US;
- On ES (Latin America) iPhone NATIVE it returned es-XL;
- On Android EN NATIVE it returned en-US;

ngx-translate has a function getBrowserLang who returns only the lang, without locale; who uses navigator.language 
https://github.com/ngx-translate/core/blob/920b95df45e98a097ef11824ba741bb0a9025b92/projects/ngx-translate/core/src/lib/translate.service.ts#L492 

How to do
- set EN as default
- get browser lang;
- use browser lang;

Problem
- we can't set a unavailable language:
  - simple solution is set EN as default and just USE the device/browser lang ( I choose), if the browser lang is not available, it will use EN as [fallback](https://github.com/ngx-translate/core#2-init-the-translateservice-for-your-application)  
  - another way, keep a updated array with available languages and check if device language is available, if not use EN;

**Comment by vdias38** [comment]
[cordova-plugin-globalization not needed anymore](https://cordova.apache.org/news/2017/11/20/migrate-from-cordova-globalization-plugin.html)  should be replaced by API browser
