### ISSUE TITLE
Clean db: comments, posts and contacts are not consistants

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#151]
### Expected behaviour
Tell us what should happen

### Actual behaviour
comments reference missing contacts and/or posts

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- to avoid this behavior, we must to turn services - [comments, posts and contacts] mock/real together

**Comment by danconte72** [comment]
- I've removed inconsistent comments and contacts from Firebase
