### ISSUE TITLE
Add mask to edit user birthday

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#161]
### Expected behaviour
See [ngx-mask](https://www.npmjs.com/package/ngx-mask)
User should type `1206` and display `12/06`

**Comment by vdias38** [comment]
- Could we select mask with localization ?
  - for instance if en mm/dd, if pt dd/mm
- on db w should save on en format `mmdd` to be consistent

**Comment by danconte72** [comment]
- https://www.joshmorony.com/improve-mobile-form-ux-with-input-masks/

- https://github.com/text-mask/text-mask/tree/master/angular2#ionic-2 

![image](https://user-images.githubusercontent.com/32454870/44583391-7f199880-a77b-11e8-8a08-bd35070414b7.png)

**Comment by danconte72** [comment]
another option: https://www.npmjs.com/package/brmasker-ionic-3

**Comment by vdias38** [comment]
Another lib: https://github.com/tiaguinho/ionic2-mask-directive

**Comment by danconte72** [comment]
Ionic datetime - [component](https://ionicframework.com/docs/api/components/datetime/DateTime/)

**Comment by danconte72** [comment]
To use ionic datetime, we must add year on our date.
My suggestion is add born year and update the Anniversaries Cloud Function


but on user view we only show month and day, no year
