### ISSUE TITLE
missing user.picture on new comment

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#163]
### Expected behaviour
My profile.picture should appear on live feed when I add comment

### Actual behaviour
I've created a new comment and my profile.picture is missing on live feed
![infomobi__improve_employee_experience](https://user-images.githubusercontent.com/9011612/44467799-b6713380-a61b-11e8-8c07-a6d38c2f135d.png)

### Steps to reproduce
1. login
2. add comment
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- Why it happens:
because current user has no picture and if there is no image, it should show a fallback icon
- How to fix it:
set a fallback icon when user has no picture. 
(Current user having no picture will be fixed on #167)
- How to test
1. login with a no picture account
2. add a comment
