### ISSUE TITLE
contacts duplicated

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#166]
### Expected behaviour
Tell us what should happen

### Actual behaviour
My account is duplicated, same issue occurs w/ SIMONE SALVADOR

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I couldn't reproduce the bug so far

**Comment by vdias38** [comment]
couldn't reproduce

**Comment by danconte72** [comment]
When I had my authData on storage, and loaded app without connection, it created a new user register for me. When I connect, it persisted the new register on firebase collection

**Comment by danconte72** [comment]
if I delete a contact who logged in and logged out and it still on login page, it will duplicate. 
looks like an observable problem.
I'm trying another ways to duplicate

**Comment by danconte72** [comment]
every time a user loged in, app it subscribes to userProfileService.fetchByEmail(). there is no unsubscribe.

**Comment by danconte72** [comment]
when a user logout and another user login in the same instance, the previous subscribe keep alive.

should unsubscribe on logout

**Comment by danconte72** [comment]
| prefix     | created       | modified       | date       | hour     | modified   | dup |
|------------|---------------|---------------|------------|----------|------------|------------|
| csantos    | 1538078241007 | 1538078437065 | 2018-09-27 | 19:57:21 | 2018-09-27 | n          |
| accarvalho | 1533753551462 |               | 2018-08-08 | 18:39:11 |            | n          |
| ebispo     | 1538078335718 | 1538593209047 | 2018-09-27 | 19:58:56 | 2018-10-03 | n          |
| drocha     | 1538082810898 | 1538592945671 | 2018-09-27 | 21:13:31 | 2018-10-03 | n          |
| dmoura     | 1550233958846 | 1550233958846 | 2019-02-15 | 12:32:39 |            | n          |
| lsipriano  | 1551239524934 | 1551239524934 | 2019-02-27 | 3:52:05  | 2019-02-27 | y          |
| lsipriano  | 1551239524941 | 1551239524941 | 2019-02-27 | 3:52:05  | 2019-02-27 | y          |
| ssilveira  | 1551257980162 | 1551257980162 | 2019-02-27 | 8:59:40  | 2019-02-27 | y          |
| ssilveira  | 1551257980187 | 1551258768513 | 2019-02-27 | 8:59:40  | 2019-02-27 | y          |
| almesquita | 1551259614211 | 1551259614211 | 2019-02-27 | 9:26:54  | 2019-02-27 | y          |
| almesquita | 1551259614228 | 1551259614228 | 2019-02-27 | 9:26:54  | 2019-02-27 | y          |
| acolivera  | 1551259818769 | 1551259818769 | 2019-02-27 | 9:30:19  | 2019-02-27 | y          |
| acolivera  | 1551259818787 | 1551259818787 | 2019-02-27 | 9:30:19  | 2019-02-27 | y          |
| gsampaio   | 1551284987770 | 1551284987770 | 2019-02-27 | 16:29:48 | 2019-02-27 | y          |
| gsampaio   | 1551284987786 | 1551284987786 | 2019-02-27 | 16:29:48 | 2019-02-27 | y          |
| machagas   | 1551285595796 | 1551285595796 | 2019-02-27 | 16:39:56 | 2019-02-27 | y          |
| machagas   | 1551285595824 | 1551285595824 | 2019-02-27 | 16:39:56 | 2019-02-27 | y          |
| elima      | 1551286263307 | 1551286263307 | 2019-02-27 | 16:51:03 | 2019-02-27 | y          |
| elima      | 1551286263345 | 1551286263345 | 2019-02-27 | 16:51:03 | 2019-02-27 | y          |

**Comment by danconte72** [comment]
There is a pattern, copy are create immediately after original.
This started on 2019-02-27, there are another scala users created that day (dconte, vdias) none duplicated, all created through web app.
Kat users who had created they users on v3 before native app launch by webapp are not duplicated.

Should check if they performed migration or login.

**Comment by danconte72** [comment]
only 4 login requests "method":"POST","url":"/api/visitors/login" on scalyr for kat users in the last 3 days
![image](https://user-images.githubusercontent.com/32454870/53511706-c7ee3900-3a9f-11e9-9e63-e4ebe1b99cd3.png)

and only chsousa has a v3 profile, not duplicated and it was created on 2018-09-29 (1538231052099) through webapp

**Comment by danconte72** [comment]
how to test migrate on #257

**Comment by danconte72** [comment]
**native testing**
- remove contact from firebase;
- install v2 apk on device;
- login on v2 - close app;
- override v2 with v3 apk (or  play store v3);
- should not request login;
- check if user creation is duplicated;

**Comment by danconte72** [comment]
native test create a duplicated user 
![image](https://user-images.githubusercontent.com/32454870/53514138-c6277400-3aa5-11e9-8987-5f67571ff1c4.png)

**Comment by danconte72** [comment]
log of migrate event on native
```logSQLitePlugin.js:175 OPEN database: storage_db
SQLitePlugin.js:106 new transaction is queued, waiting for open operation to finish
SQLitePlugin.js:179 OPEN database: storage_db - OK
SQLitePlugin.js:80 DB opened: storage_db
vendor.js:1 Ionic Native: deviceready event fired after 328 ms
main.js:1 AuthData updated {success: true, token: "604a92c2834d3bb1fba65ac26e65d25478cbb675", visitor: {…}}
main.js:1 Hello AuthProvider Provider
main.js:1 Hello PushNativeService Provider
main.js:1 Env is production ? false
main.js:1 Hello IsAdminDirective Directive
15.js:1 HomePage ngOnInit
main.js:1 getIds: {"userId":"99cdee0d-29ad-4fc9-adfc-be8e01dd64e9","pushToken":"APA91bGYEipSUsrCsUq_2F3nnsg0Px2z6nBqQDLKw8TWudGVC6IyE-IQPGXkutWfwMknWj9eF-7Mm-NB3pyrr1Ad-cXVXj0ZSNYcVTu59ell_mgvgyBZPEtd13WPhUCVmhh2W7ORgtse"}
main.js:1 AuthData updated {success: true, token: "604a92c2834d3bb1fba65ac26e65d25478cbb675", visitor: {…}}
main.js:1 set authData persistence
main.js:1 l
3.js:1 ionViewDidLoad LivePage
main.js:1 ApiService: buildUrl
main.js:1 thumbImage pipe
main.js:1 user profile successfully created
main.js:1 user profile successfully created
8.js:1 {domain: "katrium.meumobi.com"}
8.js:1 ionViewDidLoad ContactsPage
0.js:1 Hello SocialSharingNativeService Provider
main.js:1 thumbImage pipe
main.js:1 ApiService: buildUrl
main.js:1 l
main.js:1 ApiService: buildUrl
main.js:1 l
main.js:1 ApiService: buildUrl
main.js:1 l
```

**Comment by danconte72** [comment]
## How migrate works
on AuthDataPersistenceService.checkToken: 
- if data is not set on ionicstorage it calls checkV2AuthData and get the authData after migrate v2 to v3; 
- set (from ionicstorage or from checkV2AuthData) as the  next value to authData$

on AuthDataPersistenceService.checkV2AuthData
-  it check if v2 data exists on localstorage;
- migrate v2 to v3 format;
- and calls save;

on AuthDataPersistenceService.save
- it saves the authData on ionicstorage;
- set the next value to authData$;

on MyApp.listenAuthData
- it listen to authData$ and if has a value it checks (userProfileService.fetchByEmail) if profile already exists on contacts collection, if not it create a new user;

## conclusions
- according to log 'AuthData updated' is logged twice (two times next value on  authData$ is set)
- the first 'AuthData updated' (from checkToken set) userProfileService.create because profile is not on firebase collection;
- the second 'AuthData updated'  (from save set, the following log is set authData persistence) userProfileService.create because profile is not on firebase collection;

2 calls to userProfileService.create
the first return happens after the second call;
the second return happens after the second call;

if user is already set on firebase, created by login event it not duplicate, because even there are two 
'AuthData updated' the userProfileService.fetchByEmail returns true and do not call create;

## solution 
avoid duplicate set next value to authData$
