### ISSUE TITLE
Add poll component

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#171]
### Expected behaviour
Display polls from meumobi API, see meumobi/ng-meumobi-utils/blob/master/src/services/Polls.js

I recommend to create a (web?) component and save it on npm as done with File Manager

**Comment by danconte72** [comment]
Polls on [ng-meumobi-utils](https://github.com/meumobi/ng-meumobi-utils/blob/master/src/services/Polls.js)

**Comment by danconte72** [comment]
wiki [related](https://github.com/meumobi/ion-employee/wiki/How-to-handle-a-feed-with-different-item-types)

- step-by-step
  - Create Poll interface as Item-type as we see comment-types;
  - Move Post interface to be an Item-type;
  - Create Poll Component;
  - Create Article Component:
  - Move post-details content to Article Component:
  
  - Rename Post to Article;

**Comment by danconte72** [comment]
Options to show item-details
### a - one page with dyn components to only handle specific fields;
- item-details:
  - title
  - images
  - [specific fields] - with dynamic component
    - articlesComponent: description, author; --presentional component
    - pollsComponent: options, results; --presentional component
  - comments
### b - one page with dyn components to handle the entire item, despising comments;
- item-details:
  - [articleComponent] --smart component
      - title
      - images
      - description
      - author
  - comments
  - [pollsComponent] --smart component
      - title
      - images
      - options
      - results
  - comments
### c - one page with dyn components to handle the entire item, including comments (duplicating code)  (similar comments structure)
- item-details:
  - [articleComponent] --smart component
      - title
      - images
      - description
      - author
      - comments
  - [pollsComponent] --smart component
      - title
      - images
      - options
      - results
      - comments
### d - two pages without dyn components, duplicating a lot of code, items-list call the page according item-type (similar actual desk/user pages)
- Pages
  - articles-details:
      - title
      - images
      - description
      - author
      - comments
  - polls-details
      - title
      - images
      - options
      - results
      - comments

**Comment by danconte72** [comment]
propose architecture v1
![sequence diagram0](https://user-images.githubusercontent.com/32454870/44886215-79501580-ac9b-11e8-9a68-0c0e62a4bbcc.png)
![class diagram0](https://user-images.githubusercontent.com/32454870/44886216-79501580-ac9b-11e8-9b0c-524ebe2367ad.png)

**Comment by danconte72** [comment]
are we putting Polls to show on tv view?

**Comment by vdias38** [comment]
Yes polls should appear on tv view. Probably later we'll customize it to only show results.
At the moment the tv view don't do filter.

**Comment by danconte72** [comment]
- [ ] reproduce html structure from infomobi - using raw html or ionic components
- [ ] review service functions - and write how to convert from angularjs to ng-x
- [ ] implements new service into ion-employee
- [ ] move new service from ion-employee to ngx-meumobi-utils

**Comment by danconte72** [comment]
I've checked the files, and the multiple choice option does not work

**Comment by danconte72** [comment]
## poll
### js to ts transcription
totalVotes 
hasExpired
hasVoted
computeResults
getStatus
#### vote
migrate call API.Poll.submit -> api.service.poll.submit

### migrate calls
UtilsService.toast -> toastCtrl.present();
