### ISSUE TITLE
update cf todaysAnniversaries with new birthdate format 'YYYY-MM-DD', instead of 'MM-DD'

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#182]
### Expected behaviour
Tell us what should happen

### Actual behaviour
user.birthdate is saved with `YYYY-MM-DD` (ex. '1975-06-12') format but cf todaysAnniversaries query `MM-DD`

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- should get all contacts, put on array and filter using substring methods, because there is no substring o firestore queries
