### ISSUE TITLE
change preferred language not update profile preferences on db

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#183]
### Expected behaviour
Should update profile.preferredLanguage

### Actual behaviour
If I change me preferredLanguage on settings, my profile.preferredLanguage is not updated

### Steps to reproduce
1. check on db user profile.preferredLanguage value
2. on settings alter preferred language
3. check on db user profile.preferredLanguage value, should be updated

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
Today settings page only change language dynamically:
- Should connect settings page with Contacts service to update settings;
- [OR] Should move preferredLanguage from Settings to My Account Page; (easiest)

**Comment by vdias38** [comment]
I agree, should move (remove) preferredLanguage on Settings and edit it on User profile.
Seems the best way to implement is to check on profile subscriber if preferredLanguage is different than current and load it if not.
