### ISSUE TITLE
cron task to request todaysAnniversaries

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#186]
### Expected behaviour
Should be called every day at 6am

To trigger the task we have different levels of solution, from the easier to implement to more complex and complete:

1.  [cron-job.org](https://cron-job.org/en/)
2.  [cron jobs in Firebase](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html)
    - App Engine shim that provides hooks for App Engine Cron. These hooks will then push to Cloud Pub/Sub.
3.  [Scheduled Cloud Function Tasks and Cron Jobs in Firebase](https://angularfirebase.com/lessons/scheduled-tasks-and-cron-jobs-with-firebase/)
    - manage jobs and queueManager, then uses a cron-job to run the tasks. The server will regularly pull from the task queue and execute jobs that are ready to run.

### Actual behaviour
Service is called manually
https://us-central1-ion-employee.cloudfunctions.net/todaysAnniversaries

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've created an account on https://cron-job.org and set the cron to daily at 9am request https://us-central1-ion-employee.cloudfunctions.net/todaysAnniversaries.
I will wait the next execution before close the issue

**Comment by danconte72** [comment]
Cron is running properly
