### ISSUE TITLE
Setup INT environment

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#190]
### Expected behaviour
Should allow to test on integration and build for production.
Check out doc about [environments management](http://meumobi.github.io/ionic/2018/05/10/managing-aliases-environment-variables-ionc.html)

### Actual behaviour
only one env is used

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
add firebaserc on project to deploy in different envs
