### ISSUE TITLE
migrate comments on firebase to use item instead of post

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#192]
### Expected behaviour
List fields/values to update

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
On db comments migrate channel from post_ to item_

**Comment by danconte72** [comment]
comment.channel 
from post_{item_id} to item_{item_id}
comment.data
from postDetails (id, title} to itemDetails {id, title}
