### ISSUE TITLE
on INT contact-list only display on entry, instead of 3 expected

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#207]
### Expected behaviour
There are 3 contacts in INT db

![ion-employee_-_int_ _database_ _firebase_console](https://user-images.githubusercontent.com/9011612/46481183-c10e1380-c7ea-11e8-84d4-e5c6127c58eb.png)

Can't reproduce this issue on PROD db

### Actual behaviour

![infomobi__improve_employee_experience](https://user-images.githubusercontent.com/9011612/46481121-8dcb8480-c7ea-11e8-9c52-3dffaff3af2a.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I've add the index
https://console.firebase.google.com/u/0/project/ion-employee-int/database/firestore/indexes?create_index=Eghjb250YWN0cxoPCgtpc1B1Ymxpc2hlZBACGg8KC2Rpc3BsYXlOYW1lEAIaDAoIX19uYW1lX18QAg
To allow query on firestore
