### ISSUE TITLE
unexpected difference of files number on deploy

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#211]
### Expected behaviour
Tell us what should happen

### Actual behaviour

![ion-employee_ _hosting_ _firebase_console](https://user-images.githubusercontent.com/9011612/46604711-1b5eeb00-caef-11e8-9516-59ce1c264d1f.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by elbidone** [comment]
Tested on INT and it works

Latest deploys:
Oct 4, 2018 6:16 PM
Oct 4, 2018 5:27 PM

Today anniversaries was published on:
10/05/2018 @ 10:01am (UTC)

And comment without title appears 2h after todayAnniversaries post.

We put this issue on hold, waiting for new occurrences or new tests.

**Comment by danconte72** [comment]
my guess, if is a prod build or just deploy a `ionic serve` version

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/51977460-ae40de00-246e-11e9-854e-3a5fd1fd7976.png)
I've deployed on a test env. 
First with ionic serve then with ionic build. 
So the files difference is from different builds before deploy
