### ISSUE TITLE
add domain on comments model

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#213]
### Expected behaviour
Should filter by domain and match user.domain.
In order to do it should update at least model, comments-create and cf anniversaries.
On current comments (PROD firebase) set katrium domain.

### Actual behaviour
Any user retrieve all comments.

**Comment by danconte72** [comment]
- [x] Update Model
- [x] Update Create event
- [x] List by domain
- [x] Update cf anniversary - should split anniversaries for each domain
- [x] Update DB katrium 
- [x] Update [Index](https://console.firebase.google.com/u/0/project/ion-employee/database/firestore/indexes?create_index=Eghjb21tZW50cxoKCgZkb21haW4QAhoNCglwdWJsaXNoZWQQAxoMCghfX25hbWVfXxAD) on DB 
- [x] Test on ion-employee-int

**Comment by danconte72** [comment]
script to add domain on comments
```js
  db.collection('comments')
  .get()
  .then(function(querySnapshot) {
    querySnapshot.forEach(function(doc) {
      db.collection("comments").doc(doc.id).update({"domain":'katrium.meumobi.com'});
    });
  })
  .catch(function(e) {
    console.log(e);
  });
```

**Comment by vdias38** [comment]
why only if `isPublished` ?
all comments must have a domain, published or not.

**Comment by danconte72** [comment]
> why only if `isPublished` ?
> all comments must have a domain, published or not.

my mistake, I've already updated

**Comment by danconte72** [comment]
to use firestore by console 
- create a key [here](https://console.cloud.google.com/iam-admin/serviceaccounts/details/111652085061254932896?hl=pt-br&project=ion-employee-int )
- download json
![image](https://user-images.githubusercontent.com/32454870/49747852-7649c580-fc8b-11e8-8953-c806c2f02b92.png)
- config script
```js
const admin = require('firebase-admin');

var serviceAccount = {
 //downloaded json data
}

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});
var db = admin.firestore();
```
- add script to manipulate

**Comment by vdias38** [comment]
In order to test it I should

- [x] deploy PR on int.employee
- [x] run node script to set default domain on existing comments
- [x] publish new anniversaries: check for one and two today anniversaries. Previously check/set today birthdate profiles
- [ ] post new comment w/ 2 different profile's domains
