### ISSUE TITLE
update build to distinguish PWA, Native builds

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#229]
### Expected behaviour
consider
- disable service worker if native
- enable cordova.js if native

Please refer to http://meumobi.github.io/ionic/pwa/2018/03/26/using-ionic-app-sources-as-pwa.html

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- gulp scrips ok
- switch mode using `$ gulp preprocess --mode=[mode]` ok
- cli hooks do not call preprocess as seen on tutorial

**Comment by danconte72** [comment]
## Commands
```
$ npm run ionic:build:pwa
$ npm run ionic:build:native
$ ionic {serve,build} -- --mode={pwa,native}
```
