### ISSUE TITLE
Migrate Push from PushWoosh to OneSignal

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#231]

**Comment by sandstrom** [comment]
@elbidone Out of curiosity, was it easy to migrate?

**Comment by elbidone** [comment]
Hi @sandstrom, not complex but should implement the onesignal API. Fortunatly the onesignal doc and admin interface are much better than pushwoosh. I recommend!

**Comment by sandstrom** [comment]
@elbidone Thanks, much appreciated!

**Comment by elbidone** [comment]
you can have a look on [our Angular 1 implementation](https://github.com/meumobi/ng-meumobi-utils/blob/master/src/lib/Cordova/Push.js), we use a module with 2 factories with same signature: pushwoosh, onesignal. And load it with `$injector` where CONFIG.PUSH.provider = 'pushwoosh' OR 'onesignal'. This allow to switch easily config providers.

```
var push = $injector.get(CONFIG.PUSH.provider);
push.config(CONFIG.PUSH.googleProjectNumber, CONFIG.PUSH.appId);		
push.register(cb_push.register.success, cb_push.register.fail);
```

**Comment by danconte72** [comment]
Settings Model
```
export class Settings {
  moderation: boolean;
  youtubeChannelId: string;
  streaming: string;
  domain: string;
  _id?: string;
}

```
