### ISSUE TITLE
add settings page managed on firestore

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#231]
### Expected behaviour
The settings page is managed by admin, and is a document json with all required properties as
- moderation = {enabled/disabled}
- video.provider = {youtube, m3u8}
- video.url

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
## Structure
- settings model: (domain as document id)
  - moderation: boolean;
  - video.provider: [yt/m3u8];
  - video.source: string; 
- settings.service:
  - settings$: subject ( so we can get instant values)
  - fetchSettingsByDomain - authUser.domain
    - triggered when authData is set 
  - save - create/update settings doc on firebase;
- domain.settings.pages:
  - access by side menu;
  - available only for authUser.role = admin

- videoservice
 - get settings from settings service

**Comment by danconte72** [comment]
- Actual
   - SettingsPage - personal options as notifications
- Propose
   - SettingsPage -> PreferencesPages
   - SettingsPages - domain options

**Comment by vdias38** [comment]
In my opinion, we should use auto-generated key as doc.id. I can't see any benefit to break this rule.
Attributes:
- moderation: boolean;
- youtube: {url: string};
- streaming: {url: string};

Separating youtube and streaming allow us on the future to mix both providers on infomobi.
I use object for each, because it allow to add attributes without updating the model, for instance we can imagine to add the id of yt channel, or title of streaming.
