### ISSUE TITLE
raise error if media type not exist on MIMES referenced by FilesProvider

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#232]
It doesn't work if media type not exist on MIMES, no callback implemented.
Should re-check original lib, this behavior has been implemented.

If you try to open item with media mp4 it raises an error `TypeError: Cannot read property 'download' of undefined`
![infomobi__improve_employee_experience_and_ion-employee_ _node_ _ionic_term_program_apple_terminal_nvm_cd_flags__ _100x42](https://user-images.githubusercontent.com/9011612/51536877-d7e18000-1e44-11e9-8803-6901fa6a0ddb.png)

**Comment by danconte72** [comment]
Review Ionic-meumobi-utils files to keep the same behavior that ng-meumobi-utils
