### ISSUE TITLE
images broken on items/list

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#235]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![devtools_-_file____android_asset_www_index_html__home_nav_n6_items](https://user-images.githubusercontent.com/9011612/51556880-476e6400-1e73-11e9-994d-58cf01c49738.png)

works well on items/details
### Steps to reproduce
1. run app on real device and int env
2. login 
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
The issue provides from bad url of item.thumbs served by meumobi, protocol was missing:

```
"thumbnails":[  
            {  
               "width":"80",
               "height":"60",
               "url":"\/\/meumobi.com\/uploads\/items\/80x60_7006920.jpg"
            },
```

@danconte72 this issue already occured on meumobi, see meumobi/sitebuilder/issues/617. Why it re-appears ? I've re-opened the sitebuilder issue, please check what happens.

**Comment by danconte72** [comment]
The previous issues solved media.thumbnails protocol but not item.thumbnails. 
I've checked em media.thumbnails protocol has no regression.

**Comment by danconte72** [comment]
solved on https://github.com/meumobi/sitebuilder/issues/617
