### ISSUE TITLE
media attributes missing

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#237]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Missing title and thumb. Tested with video/mp4
![devtools_-_file____android_asset_www_index_html__home_nav_n6_items](https://user-images.githubusercontent.com/9011612/51557256-4c7fe300-1e74-11e9-9d46-4422e6546d3a.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
when I've posted through the ui, attributes were available 
![image](https://user-images.githubusercontent.com/32454870/51691508-0a74af80-1fe2-11e9-9047-fd6e9c490988.png)

**Comment by danconte72** [comment]
on example title is null
![image](https://user-images.githubusercontent.com/32454870/51691924-ea91bb80-1fe2-11e9-8680-9df078e248d3.png)

**Comment by danconte72** [comment]
Images we have the generic icon, how to do with empty title?

**Comment by danconte72** [comment]
> omit title if not exist or null

this is the current behavior
