### ISSUE TITLE
Duplicated AuthData update on listenAuthData

### ISSUE THREAD

**Issue by danconte72** [meumobi/infomobi#238]
### Expected behaviour
AuthData must be emit a new value only when data is updated 
### Actual behaviour
When listen to AuthData on App.component.ts there are 2 times log of authData updated
![image](https://user-images.githubusercontent.com/32454870/51605195-7cbb9600-1ef5-11e9-9db8-bca90f16de77.png)

And there is no difference between data.
### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
AuthDataPersistence.checkToken() was called twice
1. APP_INITIALIZER
2. constructor

I've removed the constructor useless call
