### ISSUE TITLE
can't use dynamic links on int

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#241]
### Expected behaviour
Tell us what should happen

### Actual behaviour
When I try to upload img testing app on int it raises an error as shown below:

![infomobi__improve_employee_experience](https://user-images.githubusercontent.com/9011612/51720708-9ae4db80-2046-11e9-9a7a-4bdb2e56e5a0.png)

```
  "error": {
    "code": 400,
    "message": "Your project does not own Dynamic Links domain: https://infomobi.page.link [https://firebase.google.com/docs/dynamic-links/rest#create_a_short_link_from_parameters]",
    "status": "INVALID_ARGUMENT"
  }
}
```
### Steps to reproduce
1. serve app on int
2. edit your account
3. upload img

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- setup dynlinks on firebase-int;
- update ENV.dynamicLinks on ion-employee;
- check if need add a new bucket on imgflow

**Comment by danconte72** [comment]
- must to [add](https://github.com/meumobi/ion-employee/wiki/Image-flow-server:-Operating-hand-book#server ) a new bucket on imgflow   
- env.dynamicLinks must set to `https://intinfomobi.page.link` we can't use . - _ on dynlinks name

**Comment by danconte72** [comment]
new imgflow bucket mounted 
```
cargo run --bin imageflow_server start --port 39876 --data-dir=./imageflow_data --mount /meumobi/:ir4_http:https:://meumobi.com/uploads/ --mount /firebase/:ir4_http:https:://infomobi.page.link/  --mount /int-firebase/:ir4_http:https:://intinfomobi.page.link/ 
```
Updated on wiki.

**Comment by danconte72** [comment]
image uploaded on int and with dynlink https://imageflow.meumobi.com/int-firebase/Zi7X
