### ISSUE TITLE
if logout can't re-login

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#242]
### Expected behaviour
Tell us what should happen

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
For OTP purpose authData are setted on API on 1st login but not resetted when logout

On relogin the Request URL: https://meumobi.com/api/comuniquese.meumobi.com/visitors/login/

**Comment by danconte72** [comment]
should call api.reset() on api.login() before http request
