### ISSUE TITLE
comment's type string is inconsistent on firestore

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#243]
### Expected behaviour
Tell us what should happen

### Actual behaviour
anniversaries vs Message
Should use lower case for any value.

![ion-employee_ _database_ _firebase_console](https://user-images.githubusercontent.com/9011612/51754508-63ad1380-20b4-11e9-9bf7-d91939042307.png)
![ion-employee_ _database_ _firebase_console](https://user-images.githubusercontent.com/9011612/51754565-80e1e200-20b4-11e9-9cff-d1cdbc43ae31.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
Update comment-details comment-form and service to use 'message';
Create script on firebase/tools to update firestore
