### ISSUE TITLE
service worker not enabled on web.infomobi

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#249]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![infomobi__improve_employee_experience_and_hangouts_video_call](https://user-images.githubusercontent.com/9011612/51982941-523a8180-248f-11e9-816d-335481ab0e80.png)

**Comment by danconte72** [comment]
I've update [onesignal config](https://onesignal.com/apps/e83fce5e-ebc8-475b-b615-fa5f1e11a129/settings/webpush/configure) to accept push signatures from web.meumobi.app

After this, the service worker is enabled. But only when user accept Push notifications .
![image](https://user-images.githubusercontent.com/32454870/51986400-4fd42980-2487-11e9-88ba-a0a38d4bf7d7.png)

**Comment by vdias38** [comment]
service worker enabled only if user accept push is an issue, please check with [OneSignal support](https://github.com/OneSignal/OneSignal-Website-SDK/issues) or forums if exist a solution. I'll create a new issue about
