### ISSUE TITLE
sw not enabled if user don't subscribe to push

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#251]
see #249

**Comment by danconte72** [comment]
there is a [issue](https://github.com/OneSignal/OneSignal-Website-SDK/issues/231)  and a [fix](https://github.com/OneSignal/OneSignal-Website-SDK/issues/231#issuecomment-300854799) recommended by a onesignal [dev](https://github.com/jasonpang)

**Comment by danconte72** [comment]
> there is a [issue](https://github.com/OneSignal/OneSignal-Website-SDK/issues/231) and a [fix](https://github.com/OneSignal/OneSignal-Website-SDK/issues/231#issuecomment-300854799) recommended by a onesignal [dev](https://github.com/jasonpang)

that solution not worked properly.
Even when user accept `ngsw-worker` started

**Comment by danconte72** [comment]
I've re-tested and it worked
#### When browser permission push is granted and user opt-in
![image](https://user-images.githubusercontent.com/32454870/52054386-7788c780-2543-11e9-90e9-adcf46cc0be2.png)

#### When browser permission push is granted and user opt-out
![image](https://user-images.githubusercontent.com/32454870/52054493-da7a5e80-2543-11e9-92f8-83a0f76f0b0a.png)

#### When browser permission push is denied and user opt-in
![image](https://user-images.githubusercontent.com/32454870/52054873-fdf1d900-2544-11e9-83c0-c9d8fdac9c9e.png)

#### When browser permission push is denied and user opt-out
![image](https://user-images.githubusercontent.com/32454870/52054994-48735580-2545-11e9-94a4-d51ccb7f0e78.png)

### Commands used 
```js
OneSignal.setSubscription(false);
OneSignal.setSubscription(true);
OneSignal.getSubscription(function(data) {console.log(data);});
OneSignal.getNotificationPermission(function(data) {console.log(data);});

```

**Comment by danconte72** [comment]
- To test u must to reload after change permissions.
- OneSignal.appId able to work with localhost = `d8a97696-79c3-4f61-93c2-77ae0a4b50d3` (test purposes account)
- To change chrome push permissions access [chrome://settings/content/notifications?
](chrome://settings/content/notifications?)
