### ISSUE TITLE
Build and Publish for tests Android App

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#254]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
1. update local firebase config to prod
2. perform `$ npm run preionic:build:native`
3. perform `$ ionic cordova build --release --prod android`


https://ionicframework.com/docs/publishing/play-store

**Comment by danconte72** [comment]
It will build a apk on `platforms/android/app/build/outputs/apk/release/`   
called `app-release-unsigned.apk`
to sign I've copied `meumobi.keystore` to the same dir then performed
```
$ cd platforms/android/app/build/outputs/apk/release/
$ jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore meumobi.keystore app-release-unsigned.apk meumobi
```
then we need to zipalign, it came with android sdk build-tools, for me I've performed
```
$ /Users/danielconte/Library/Android/sdk/build-tools/28.0.3/zipalign -v 4 app-release-unsigned.apk new.apk
```
Then uploaded `new.apk` to play[dot]console

**Comment by danconte72** [comment]
0.4.0 debug ok
0.4.0 release ok
feat/push-pwa debug ok 
feat/push-pwa release ok 

I've performed `npm install`, `ionic cordova platform rm android` AND `ionic cordova platform add android` between tests
