### ISSUE TITLE
migrate authData storage form v2 to v3

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#257]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
On AuthDataPersistenceService in checkToken():
- Check if token is saved on v3 storage/format;
- If is not, check if token is saved on v2 storage/format;
- If is saved, migrate from v2 to v3 format, and save();


#### v3
- storage = ionic/storage
- format 
```js
{ 
  "X-Auth-Token:" {
    success: boolean;
    token: string;
    message?: string;
    visitor: AuthUser;
    error?: string;
  }
}
```

#### v2
investigating

**Comment by vdias38** [comment]
v2 use 2 keys

- visitor: json
- authToken: string

Ex. visitor
```json
{"first_name":"Victor","last_name":"Dias","email":"victor.dias+employee@meumobi.com","site":"meumobibox.meumobi.com"}
```

![infomobi](https://user-images.githubusercontent.com/9011612/52223260-23f8df80-289d-11e9-97d4-3355b6e84009.png)

**Comment by vdias38** [comment]
When migrated, remove visitor and authToken from local storage

**Comment by vdias38** [comment]
to test, 


1. Set current credentials on localstorage

Set following key/value on localstorage

- visitor: {"first_name":"Victor","last_name":"Dias","email":"victor.dias+katrium@meumobi.com","site":"katrium.meumobi.com"}
- authToken: 72160da4079e80891d14b1ef3edd6dfb44da98bd

2. Erase indexedDb/storage_db

![infomobi__improve_employee_experience](https://user-images.githubusercontent.com/9011612/52282945-6aac0f80-2959-11e9-858c-bdb662bb3319.png)

3. Fore reload
and check localstorage have been erased and indexedDb/storage_db should have following key/value

- X-Auth-Token: 
"{"success":true,"token":"72160da4079e80891d14b1ef3edd6dfb44da98bd","visitor":{"first_name":"Victor","last_name":"Dias","email":"victor.dias+katrium@meumobi.com","site":"katrium.meumobi.com"}}"

![infomobi__improve_employee_experience](https://user-images.githubusercontent.com/9011612/52283177-eefe9280-2959-11e9-9050-a90243eabb84.png)
