### ISSUE TITLE
migrate videos.service to npm package mmb-youtube-provider

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#258]
I've create the [repo](https://github.com/meumobi/mmb-youtube-provider) on meumobi account

- Should allow to setup API Key (and API url ?) via [useValue or forRoot](https://medium.com/@michelestieven/angular-writing-configurable-modules-69e6ea23ea42)

**Comment by vdias38** [comment]
Add new blog post about npm package publish

**Comment by vdias38** [comment]
[angular-linkedin-sdk](https://github.com/evodeck/angular-linkedin-sdk) is an example of package using useValue

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/52362210-37d04d00-2a27-11e9-9bc1-d54cc1a12801.png)
Even forRoot is set on App Module. It will be launched when it will be used. 
Hello YoutubeService is one time started, but just after is necessary, when open video page
