### ISSUE TITLE
img on item details could not be cropped

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#261]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![screenshot_2019-02-06-13-01-16](https://user-images.githubusercontent.com/9011612/52343597-642c9f00-2a10-11e9-9e0a-ef7458c45416.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
Should set imageViewer url without height on img element something like
```html
<img src="..." srcset="..." imageViewer="{img.src}?width=${width}&scale=both&format=jpg "></img>
```

**Comment by vdias38** [comment]
`ENV.imgServer.sources[source].prefix` allows only one value for each source, but meumobi has 2 prefix: `/uploads` (images) and `https://meumobi.com/uploads/` (thumbnails).

Then we should refactor the class `ImgServerSrcsettifyPipe` to allow an array of `prefixes` instead of single value `prefix`
`const prefixes = ENV.imgServer.sources[source].prefixes;`

Extract of environment.ts
```
      meumobi: {
        prefixes: ['/uploads', 'https://meumobi.com/uploads']
      },
```

Replace on class `ImgServerSrcsettifyPipe`
```
if (src.startsWith(prefix)) {
          src = src.replace(prefix, source);
          onServer = true;
        }
```

By
```
/*
* getSource(src) check if any prefix from config match src, if true return a 2-uple `{source: prefix}`
*/
if (source = getSource(src)) {
  src = src.replace(source[value], source[key]);
  onServer = true;
}
```

Then add it on articles and polls headlines

```
<img *ngIf="item.thumbnails.length" [src]="item.thumbnails[item.thumbnails.length-1].url" [srcset]="item.thumbnails[item.thumbnails.length-1].url | imgServerSrcsettify" />
```


Below an example of thumb and images results of item

```
            "thumbnails": [
                {
                    "width": "80",
                    "height": "60",
                    "url": "https://meumobi.com/uploads/items/80x60_7007013.png"
                },
                {
                    "width": "80",
                    "height": "80",
                    "url": "https://meumobi.com/uploads/items/80x80_7007013.png"
                },
                {
                    "width": "139",
                    "height": "139",
                    "url": "https://meumobi.com/uploads/items/139x139_7007013.png"
                },
                {
                    "width": "314",
                    "height": "220",
                    "url": "https://meumobi.com/uploads/items/314x220_7007013.png"
                },
                {
                    "width": "1200",
                    "height": "800",
                    "url": "https://meumobi.com/uploads/items/1200x800_7007013.png"
                }
            ],
...
            "images": [
                {
                    "id": "7007013",
                    "model": "Items",
                    "foreign_key": "5c658d099a645d8e46d5e8f8",
                    "path": "/uploads/items/7007013.png",
                    "url": null,
                    "author": null,
                    "title": "",
                    "description": null,
                    "filesize": "574654",
                    "filesize_octal": "2142276",
                    "type": "image/png",
                    "visible": "1",
                    "created": "2019-02-14 16:45:08",
                    "modified": "2019-02-14 16:45:13"
                }
            ]
```

**Comment by vdias38** [comment]
- add ImgViewer for polls headlines (no details page)
- check if necessary/required `&format=jpeg` for performance purpose

**Comment by danconte72** [comment]
There is a function on Utils imgServerPrefix to deal with multiple prefix.
Should call on this on img pipes

**Comment by danconte72** [comment]
jpeg format is useful 
![image](https://user-images.githubusercontent.com/32454870/53019448-86bcb000-3433-11e9-9d7b-b9f8d68db18c.png)

**Comment by danconte72** [comment]
Even with srcset the image loaded is from src 
![image](https://user-images.githubusercontent.com/32454870/53021024-013aff00-3437-11e9-89f4-c0b5c6e6c33f.png)

**Comment by danconte72** [comment]
I've add a pipe to work with imageviewer to grantee a zoom image not cropped
