### ISSUE TITLE
polls: end date is cropped

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#262]
### Expected behaviour
Should remove useless year on date

![screenshot_2019-02-06-18-42-02](https://user-images.githubusercontent.com/9011612/52365424-5a6e6000-2a3f-11e9-9cc0-17637040f731.png)

**Comment by danconte72** [comment]
add translate for Votes

**Comment by danconte72** [comment]
You can't use Locale format "LL' without year https://github.com/moment/moment/issues/4325 
We can set "month and day" but we loose 'de' preposition on PT-BR
Date will be showed like 'Fevereiro 25' and not '25 de Fevereiro'
Another short option is use Locale 'll' who will show '25 de fev de 2019' on PT-BR and ' Feb 25, 2019' on EN-US.

It works 
![image](https://user-images.githubusercontent.com/32454870/52481707-60c32000-2b96-11e9-8a39-dd96339f22ed.png)
where it was like this
![image](https://user-images.githubusercontent.com/32454870/52481748-851efc80-2b96-11e9-8ddd-a135c3b7caee.png)
