### ISSUE TITLE
add Android Notification Icons

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#266]
https://documentation.onesignal.com/docs/customize-notification-icons

**Comment by vdias38** [comment]
Naming

/drawable-[SIZE_NAMES]/ic_stat_onesignal_default.png (Small Icons)
/drawable-xxxhdpi/ic_onesignal_large_icon_default.png (Large Icon)

If resource-file on config.xml ([source](https://stackoverflow.com/a/52872849/4982169)) not work try [cordova hook](http://flashquartermaster.com/2016/08/26/how-to-automatically-copy-onesignal-custom-notification-icons-into-the-android-resources-directories-for-ionic-projects/) launched after [cordova prepare](https://ionicframework.com/docs/cli/commands/cordova-prepare/) or [android_custom_resources.js](https://forum.ionicframework.com/t/copying-resource-to-android-platform/111619/4)

```
        <resource-file src="resources/android/notification/drawable-mdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-mdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-hdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-hdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-xhdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-xhdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-xxhdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-xxhdpi/ic_stat_onesignal_default.png" />
        <resource-file src="resources/android/notification/drawable-xxxhdpi/ic_stat_onesignal_default.png" target="app/src/main/res/drawable-xxxhdpi/ic_stat_onesignal_default.png" />
```

**Comment by danconte72** [comment]
I've add android_custom_resources script.
Removed, added and compiled android build and tested on emulator.
![image](https://user-images.githubusercontent.com/32454870/53015369-ad75e900-3429-11e9-9bfd-49f851d45e75.png)

**Comment by vdias38** [comment]
To do it with resource-file, need to update the config.xml

> you need to alter the top widget line. You'll want to add `xmlns:android="schemas.android.com/apk/res/android` to it, so it looks like the below. This allows the system to change the `AndroidMenifest.xml` file.

[Source](https://stackoverflow.com/a/51749564/4982169)
