### ISSUE TITLE
imgs avatar sometimes are broken

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#277]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Should add processing time on imageflow logs to check if time response is responsible

![screenshot_2019-02-13-12-57-50](https://user-images.githubusercontent.com/9011612/52787675-7c2aa100-3056-11e9-9757-50cb3a04902c.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
Log format used on sitebuilder including response time

1. update apache conf `/etc/apache2/apache2.conf`
`LogFormat "%{Host}i %v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" time=%Dms (%Tsec), connection=%X" vhost_combined`

2. update vhost
`CustomLog "|/usr/bin/rotatelogs /var/log/apache2/imageflow.meumobi.com/access.%Y-%m-%d 86400" vhost_combined`

3. restart apache

**Comment by vdias38** [comment]
I've updated logs to add time response and scalyr parser to track time
`      format: "$host$:$port$ $ip$ $user$ $authUser$ \\[$timestamp$\\] \"$method$ $uri{parse=uri}$ $protocol$\" $status$ $bytes$ $referrer=quotable$ $agent=quotable$ time=$time=number$ms \\($timesec=number$sec\\), connection=$connection$",`

![search_logs___scalyr](https://user-images.githubusercontent.com/9011612/52724325-09aeb800-2fa7-11e9-9058-d311fadd3f01.png)

**Comment by danconte72** [comment]
should check response time on scalyr

**Comment by danconte72** [comment]
In the last 7 days the time response average is less than 1 sec

![image](https://user-images.githubusercontent.com/32454870/53354348-54182900-3905-11e9-89fb-a703ab7a7b47.png)

**Comment by vdias38** [comment]
then we can consider this issue closed. On a next step we'll set cache
