### ISSUE TITLE
Add intro if 1st session after OTP

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#289]
https://github.com/hitmacreed/Ionic3-animated-intro-slides

**Comment by vdias38** [comment]
OnBoarding slides:
- profiles: Edit profile
- live: comments (should encourage to create ?)
- news: the communicatin Dpt share news
- news comment
- news: media download/share
- profiles: list|search
- home: (videos, if settings.youtube)

# MVP
3 slides (live, news, profiles) on launch
(+1 edit your profile if no picture or no birthdate)

**Comment by vdias38** [comment]
[Example of walkthrough on conference app](https://github.com/ionic-team/ionic-conference-app/tree/v3/src/pages/tutorial)

**Comment by vdias38** [comment]
[Undraw Illustrations](https://undraw.co/illustrations) to use on slides.
Should choose one per each slide to [illustrate the benefit](https://material.io/design/communication/onboarding.html#top-user-benefits-model)

**Comment by vdias38** [comment]
- Ao vivo (en: live, illustration: celebration): 
  - Compartilhe acontecimentos em tempo real
  - Share events in real time
- noticias (news, business plan): 
  - Seja informado com conteúdo direcionado
  - Be informed with targeted content
- contatos (contacts, online friends): 
  - Acesse os contatos da sua empresa
  - Access contacts from your company
- Atualize seus dados (Edit your profile, profile pic)
  - Vamos começar agora por editar seu perfil
  - Let's start now by editing your profile

**Comment by danconte72** [comment]
walkthrough/tutorial/onboarding
- after login should check ionicstorage var hasSeenTutorial/hasSeenOnBoarding
  - if not: openOnBoarding
      - on HomePage viewDidLoad open OnBoardingPage as Modal
      - (on ionic-conference-app it sets OnBoardingPage as root)

- OnBoardingPage
  - ionSlides to show content;
  - skip button to set hasSeenTutorial = true and open HomePage
    - close Modal
    - ( on ionic-conference-app it add HomePage to nav stack)
    - skip button is showed on all pages except last one
  - lastSlide:
    - EditProfile button set hasSeenTutorial = true and open MyProfilePage
      - close Modal and add MyProfilePage to nav stack
    - EditProfileLater button set hasSeenTutorial = true and open HomePage
      - close Modal 


Question:
- is it necessary a service to get/set hasSeenTutorial on ionicstorage? on ionic-conf-app it get set directly on page

**Comment by vdias38** [comment]
- Why don't use as root as conference App ?
- onBoarding is not displayed after login
  - on launch if logged && !hasSeenOnBoarding
  - after login (+OTP) && !hasSeenOnBoarding
- hasSeenTutorial is not a Service

**Comment by vdias38** [comment]
## Call from HomePage
```js
  displayTutorial() {
    // Check if the user has already seen the tutorial
    this.storage.get('hasSeenTutorial')
    .then((hasSeenTutorial) => {
      if (!hasSeenTutorial) {
        this.openPage(TutorialPage);
      }
    });
  }

  ionViewDidLoad() {
    this.displayTutorial();
  }
```

**Comment by vdias38** [comment]
- Bem vindo a bordo! 5 (Welcome on board!, mobile life)
    - "O infomobi permita-lhe interagir com sua organização em tempo real, de forma simples e na palma da mão. A seguir, descubra as principais funcionalidades."
  - "infomobi provides real-time interaction with your organization to stay connected wherever you are. Find out the top features next "
