### ISSUE TITLE
Cordova allow navigation to YouTube urls on iOS

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#295]
need to [allow navigation](https://github.com/apache/cordova-plugin-whitelist) to YouTube urls in our config.xmlfile by adding the below line:
`<allow-navigation href="https://*youtube.com/*"/>`
[Source](https://www.sebastianschirmer.com/blog/ionic-youtube-embed/)
If I tried to embed a youtube video using iframe tag with only this rule `<allow-navigation="://domain.com/">`, it doesn't allow loading of the video in iframe as youtube.com is not listed in allowed domains.
[Source](https://issues.apache.org/jira/browse/CB-10709)

**Comment by danconte72** [comment]
should test a ios build to check this behavior

**Comment by vdias38** [comment]
credentials are available on gdrive:/shared/RESOURCES/DEV/certificates
- meumobi_Wild_Card.mobileprovision
- victor-dias_DEV.p12

**Comment by danconte72** [comment]
build ios app https://ionicframework.com/docs/building/ios

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/53977554-0c08bb80-40e8-11e9-8364-9320e8547f82.png)
I've faced this alert on xcode

**Comment by danconte72** [comment]
![image](https://user-images.githubusercontent.com/32454870/54028027-5179c700-4182-11e9-9b23-4faebd11c2e9.png)

**Comment by vdias38** [comment]
credentials for infomobi DEV are available on gdrive:/shared/RESOURCES/DEV/certificates
- InfoMobi_DEV.mobileprovision
- victor-dias_DEV.p12
- victor-dias_APS_DEV.p12

**Comment by danconte72** [comment]
Build successful but 
![image](https://user-images.githubusercontent.com/32454870/54030487-85f18100-418a-11e9-8688-ca6984452b1a.png)

**Comment by vdias38** [comment]
Should check Xcode state (config or restart) as suggested on [this stackoverflow thread](https://stackoverflow.com/questions/19581225/the-executable-gets-signed-with-invalid-entitlements-in-xcode)

**Comment by danconte72** [comment]
I've tried a build without Push capabilities
![image](https://user-images.githubusercontent.com/32454870/54119131-6731fb00-43d3-11e9-897c-975b81485811.png)
It asked for push permissions on app and it subscribed on onesignal

![image](https://user-images.githubusercontent.com/32454870/54119110-5aada280-43d3-11e9-9c33-b64dcab6ee46.png)

**Comment by danconte72** [comment]
this solution worked for me https://stackoverflow.com/a/53410390 

> File > Project Settings... > Shared Project Settings: > Build System --> Selected "Legacy Build System" instead of the default "New Build System (Default)".

**Comment by danconte72** [comment]
youtube videos are blank before add <allow-navigation href="https://*youtube.com/*"/> the solution it worked
