### ISSUE TITLE
allow web/native social share on same src code

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#299]
based on pattern used for [push native/pwa](https://github.com/meumobi/ion-employee/pull/274) add web share. [Navigator.share](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) seems to be the straightforward solution even if only supported on mobile. So should add a fallback if not supported (=> raise error 'Not supported device' ?)

- [Web Share API brings the native sharing capabilities to the browser](https://hospodarets.com/web-share-api)

**Comment by danconte72** [comment]
- move SocialSharingService -> SocialSharingNativeService (SSNS)
- create new SocialSharingPwaService (SSPS)
- create an abstract Class SocialSharingService (SSS)
  - abstract methods so far: shareItem and shareMedia
  - socialSharingServiceFactory: according platform it returns the correct service SSPS = Pwa, SSNS = Native
  - SocialSharingServiceProvider
- SSPS and SSNS must to implements SSS

**Comment by danconte72** [comment]
I've tested and 'web share api' worked only on chrome on android.
How to implements the fallback? (iOS, desktop browsers)
Like 'copy link' function on gdrive/twitter?
![image](https://user-images.githubusercontent.com/32454870/53248858-7f94dc80-3695-11e9-87e3-7e7661ee3f19.png)
![image](https://user-images.githubusercontent.com/32454870/53248999-bb2fa680-3695-11e9-833d-31b4ab0c9228.png)
Presenting a toast like 
![image](https://user-images.githubusercontent.com/32454870/53249078-ffbb4200-3695-11e9-88d6-c86f96c768b0.png)

**Comment by danconte72** [comment]
We can concatenate the text with url like webapishare does and put on clipboard
![image](https://user-images.githubusercontent.com/32454870/53249304-896b0f80-3696-11e9-8bd7-ae944678d9c8.png)
