### ISSUE TITLE
Dynamic Theming

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#305]
we have option to create themes, for ex. red, orange, blue and green and select theme on settings
- https://devdactic.com/dynamic-theming-ionic/
- https://github.com/yannbf/ionic3-components/tree/master/src/theme
- https://medium.freecodecamp.org/how-to-dynamically-theme-your-ionic-application-and-make-your-users-happy-ffa17e15dbf7

Using css variables seems too hard on Ionic3 because it uses scss
- https://stackoverflow.com/questions/53502364/dynamically-changing-css-value-in-ionic-3

**Comment by danconte72** [comment]
- Add themes on src/theme:
  - theme.theme1.scss
  - theme.example.scss
- add theme property on settings, manipulate on settingsPage, settingsService
- theme property will be accessed by settingsService.getSettingsObserver()
- subscribe theme on app.component.ts
- add [class]="selectedTheme" on app.html

I need the prefixed colors, I'm testing with current color (theme1-theme) and infomobi v2 orange (theme2-theme)

**Comment by danconte72** [comment]
theme.[example].scss must to include css properties as this example. Should check which properties must to be set for our case
```css
.example-theme {
  ion-content {
    background-color: #fff;
  }
 
  .toolbar-background {
    background-color: #fff;
  }
}
```

example-theme is the theme name

**Comment by danconte72** [comment]
> it’s simply not possible. sass is transpiled to css at build time so the variables become part of the final CSS, and hence they’re static. This means that they are statically coded in the CSS.
https://forum.ionicframework.com/t/overriding-component-sass-variables-in-dynamic-themes/115186/5 

In this topic there are a lot of bad workarounds

**Comment by danconte72** [comment]
Josh Morony has an example for ionic v4 https://www.joshmorony.com/creating-a-theme-switcher-service-in-ionic-using-css4-variables/

**Comment by danconte72** [comment]
Options so far, ordered by preference
- not dyn theming app, only updating logo and using a generic color as primary, and wait client feedbacks, and have theme only on v4 
- not theming the entire app,  updating logo, generic color as primary and dynamically changing the toolbar and fab color (using simmon green solution); 
- theming use simmon green solution, but using a script to produce the theme, there 200+ elements using primary color; it will produce a larger css after build;
- setting a theme before deploy, needing a different deploy for each client :/

**Comment by vdias38** [comment]
Then I recommend to use the solution using css variables
* https://stackoverflow.com/questions/53502364/dynamically-changing-css-value-in-ionic-3
We could write a custom.css with a primary color (for ex. infomobi yellow) and text color (for ex black for infomobi), import it as theme and dynamically form app.component set values of these vars with 

```
document.documentElement.style.setProperty(`--primary-color`, primaryColor);
document.documentElement.style.setProperty(`--text-color`, textColor);
```

**Comment by vdias38** [comment]
- should test if none settings.colors setted, does css get default value ([IE workaround](https://vgpena.github.io/winning-with-css-variables/), due to [lack of support of css variables on IE](https://caniuse.com/#feat=css-variables)) as fallback
