### ISSUE TITLE
This app has crashed because it attempted to access privacy-sensitive data without a usage description

### ISSUE THREAD

**Issue by danconte72** [meumobi/infomobi#323]
### Expected behaviour
Tell us what should happen

### Actual behaviour
 [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data. (on accessing camera)

### Steps to reproduce
1. Open the app on iOS
2. New Comment
3. Add picture from camera

### Expected responses
- Why it happens
This app has crashed because it attempted to access privacy-sensitive data without a usage description.
- How to fix it
The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data. 
- How to test

**Comment by danconte72** [comment]
I've add this explanation manually through xcode ui 
![image](https://user-images.githubusercontent.com/32454870/54127385-6a83b180-43e8-11e9-87cb-2ab55dd02cc7.png)
It worked but it's not a definitive fix

**Comment by danconte72** [comment]
https://stackoverflow.com/questions/39566952/cordova-info-plist-nscamerausagedescription-key-is-missing 

> Since Cordova CLI 6.5.0 you can write in the info.plist directly by using the edit-config tag in the config.xml like this:
```xml
<edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>your usage message</string>
</edit-config>
```

**Comment by vdias38** [comment]
Here the full doc of [cordova-plugin-camera](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-camera/index.html)

**Comment by danconte72** [comment]
https://stackoverflow.com/a/39583887 

> Yes, you can modify info.plist from the config.xml file using the config-file tag, but you have to use a plugin for that (cordova custom config) and follow the instructions religiously.

>However, probably a better option is to use plugin.xml to do the same thing. More about it you can read here (modifying info plist from plugin.xml)

Looks like we must to add manually the plugin on project

**Comment by vdias38** [comment]
I've wrote a [post about updating info.plist](http://meumobi.github.io/tips%20and%20tricks/2016/05/05/add-entry-ios-plist-cordova.html) a time ago.

Then seems we should choose between:
- create and add an empty plugin setting plist properties (following tutorial above)
- adding cordova-plugin-camera and adding on config.xml config

To keep the app the lower as possible I should recommend the empty plugin

**Comment by danconte72** [comment]
This [plugin](https://github.com/MBuchalik/cordova-plugin-ios-permissions) could be fix this error. 
It handles localization too. 
There is EN and PT, DE  translations so far. 
Should check if PT works with a PT-BR device, if not, fork and PR to this plugin with languages we need.

**Comment by danconte72** [comment]
The plugin it contains an NSCameraUsageDescription and NSPhotoLibraryUsageDescription keys with a string value explaining to the user how the app uses this data.

**Comment by danconte72** [comment]
I've tested the plugin and it worked
![image](https://user-images.githubusercontent.com/32454870/54198350-0541c600-44a5-11e9-9880-2139b805e801.png)

**Comment by hrana123** [comment]
Step 1: Create the entitlement.plist file in Document and paste these keys.
   
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.inherit</key>
        <true/>
<key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.debugger</key>
    <true/>

    <key>com.apple.security.device.camera</key>
    <true/>
  <key>com.apple.security.device.microphone</key>
    <true/>

  <key>com.apple.security.network.server</key>
    <true/>
  <key>com.apple.security.network.client</key>
    <true/>  
<key>com.apple.security.device.usb</key>
    <true/>
  <key>com.apple.security.print</key>
    <true/>
  <key>com.apple.security.device.bluetooth</key>
    <true/>  
<key>com.apple.security.files.user-selected.read-only</key>
    <true/>

  <key>com.apple.security.files.user-selected.read-write</key>
    <true/>  
<key>com.apple.security.files.downloads.read-only</key>
    <true/> 
 <key>com.apple.security.files.downloads.read-write</key>
    <true/> 
<key>com.apple.security.assets.pictures.read-write</key>
    <true/>  
<key>com.apple.security.assets.music.read-only</key>
    <true/>

  <key>com.apple.security.assets.music.read-write</key>
    <true/>
  <key>com.apple.security.assets.movies.read-only</key>
    <true/>
  <key>com.apple.security.assets.movies.read-write</key>
    <true/>


    </dict>
</plist>

Step 2: Right click in the application go to contents then go to info.plist file and add this key.
   <key>NSCameraUsageDescription</key>
   <string><Application_name> application requests access to the device's camera.</string>

Step 3: Run this command in terminal .
            sudo codesign --sign - \
    --entitlements /Users/devadmin/Documents/entitlements.plist \
    --deep /Applications/Talygen.app \
    --force

Step 4: After that run the application and access the camera.
