### ISSUE TITLE
use sass variable to apply primary dark variant on alert buttons

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#326]
theme/variables.scss use hard coded colors

```
$alert-md-button-text-color: #9b7800;
$alert-ios-button-text-color: #9b7800;
```

should replace by primary color dark

**Comment by danconte72** [comment]
ionic default theme use base (primary) color for this element
https://github.com/ionic-team/ionic/blob/0fec72255bb99611cfe67ea70152400ec7f8b762/core/src/components/alert/alert.md.vars.scss#L155

if we use dark color, we must to add on settings theme too.
My suggestion is use base color as ionic default theme

**Comment by vdias38** [comment]
ok for base
