### ISSUE TITLE
custom logo not appears on iOs

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#329]
### Expected behaviour
Tell us what should happen

### Actual behaviour

![Photo from Victor Dias](https://user-images.githubusercontent.com/9011612/54357963-2518eb80-4657-11e9-89cb-9dd825e8e300.jpg)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by vdias38** [comment]
Seems to be a CORS issue zyra/ionic-image-loader/issues/131. Need to investigate, and read logs to confirm.

**Comment by vdias38** [comment]
Can't reproduce issue, tested on simulator (running w/ Xcode) and on device (iOS 12).
Please @danconte72 redo test and confirm if it works for you, if not check logs of web inspector console and copy the error here

**Comment by vdias38** [comment]
I observed it on PROD, will check with prod build if I can reproduce on local

**Comment by vdias38** [comment]
This issue is due to [CORS restrictions on iOS with WKWebView](https://github.com/zyra/ionic-image-loader/issues/131)
Works well if img hosted on meumobi because use http header `Access-Control-Allow-Origin: *`, AWS S3 by default not, but could [update AWS S3 CORS](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html)

**Comment by vdias38** [comment]
migrate scala, stihl and comunique-se logos to /infomobi/ S3

**Comment by danconte72** [comment]
just add this rule on bucket 
```html
<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>*</AllowedOrigin>
   <AllowedMethod>GET</AllowedMethod>
 </CORSRule>
</CORSConfiguration>
```
HERE
![image](https://user-images.githubusercontent.com/32454870/55004267-adcd4b00-4fb8-11e9-8fa6-876c73503c93.png)

Test on 3.0.8 iOS/app 
![image](https://user-images.githubusercontent.com/32454870/55004368-e2410700-4fb8-11e9-89d6-7ccbd7389a76.png)

**Comment by danconte72** [comment]
moved logos to s3/infomobi/logos

and updated on settings

**Comment by danconte72** [comment]
I've tested with c-se too
![IMG_819507526EDB-1](https://user-images.githubusercontent.com/32454870/55006463-909a7b80-4fbc-11e9-84e8-c8b48a285b58.jpeg)
