### ISSUE TITLE
tv and videos icons cropped

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#330]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![Photo from Victor Dias](https://user-images.githubusercontent.com/9011612/54357963-2518eb80-4657-11e9-89cb-9dd825e8e300.jpg)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
should reduce font-size in order to avoid icon crop
