### ISSUE TITLE
custom theme not applied on menu, tv, videos icons on iOS

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#331]
### Expected behaviour
Tell us what should happen

### Actual behaviour
![Photo from Victor Dias](https://user-images.githubusercontent.com/9011612/54357963-2518eb80-4657-11e9-89cb-9dd825e8e300.jpg)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
- menu on ios use primary color https://ionicframework.com/docs/v3/api/components/menu/Menu/ 
- same behavior with buttons icons on nav bar https://ionicframework.com/docs/v3/api/components/toolbar/Navbar/

**Comment by danconte72** [comment]
add bar-button-ios to use primary color on theme

**Comment by vdias38** [comment]
# Why it happens
- [menu](https://ionicframework.com/docs/v3/api/components/menu/Menu/) icon ("hamburger") and [navbar](https://ionicframework.com/docs/v3/api/components/toolbar/Navbar/) icons (TV & videos) use primary color on iOS, not on Android (dark color).

# How to fix it
- then we need to also overwrite `bar-button-ios` to use custom primary color.
