### ISSUE TITLE
broken thumb of text/html media

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#333]
### Expected behaviour
Tell us what should happen

### Actual behaviour

![Screenshot_2019-03-15-08-27-52](https://user-images.githubusercontent.com/9011612/54418529-1a189680-46fd-11e9-8667-973e87122ca9.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
I could not reproduce. probably the cleanContent error event.
