### ISSUE TITLE
wrong image shared on item/share

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#344]
### Expected behaviour
Tell us what should happen

### Actual behaviour
An image with low resolution is used instead of highest resolution

![Screenshot_2019-03-21-18-43-10](https://user-images.githubusercontent.com/9011612/54777138-8a497f80-4c09-11e9-91ae-af1e94926bef.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
### why it happens
SocialSharingNativeService.shareItem is getting the first thumbnail of array
`params.files.push(item.thumbnails[0].url);`
For convention the first item thumbnail has the smallest size.

### how to fix
update SocialSharingNativeService.shareItem 
to use the last thumbnail (largest) as did on Articles component
`params.files.push(item.thumbnails[this.item.thumbnails.length - 1].url);`
