### ISSUE TITLE
update on-boarding screens titles

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#352]

**Comment by vdias38** [comment]
Below my suggestions

Ao vivo (en: live, illustration: celebration):
- Compartilhe acontecimentos em tempo real. O canal -Ao vivo- permite fazer perguntas ou sugestões de forma facil, estamos na escuta para atende-los. Aqui também todos podem comemorar realizações ou compartilhar experiências positivas.

noticias (news, business plan):
- Seja informado com conteúdo direcionado. No canal de -Noticias- publicamos informações relevantes sobre as atividades da empresa.

contatos (contacts, online friends):
- Acesse os contatos da sua empresa. Seja de colegas ou setores especificos, todas informações de contato estão disponiveis no canal de -Contatos-.

**Comment by danconte72** [comment]
v2 - num formato mais coloquial
- Compartilhe acontecimentos em tempo real. 
No canal -Ao vivo- todos podem compartilhar experiências positivas, comemorar realizações e ainda fazer perguntas ou sugestões de forma fácil. Acompanhe também o que está acontecendo em sua organização no momento. Há sempre alguém de aniversário.

- Seja informado com conteúdo direcionado. Em -Notícias- publicamos informações relevantes sobre as atividades da empresa. Aqui você também pode comentar.

- Acesse os contatos da sua empresa. Seja de colegas ou setores específico, todas informações de contato estão disponíveis no canal -Contatos-.

**Comment by vdias38** [comment]
my only update "Acompanhe também o que está acontecendo em sua organização no momento, há sempre alguém de aniversário ;-)" instead of "Acompanhe também o que está acontecendo em sua organização no momento. Há sempre alguém de aniversário."

**Comment by danconte72** [comment]
I suggest reduce live to: "Aqui todos podem comemorar realizações, fazer perguntas ou sugestões de forma fácil. Acompanhe o que está acontecendo em sua organização no momento, há sempre alguém de aniversário 😉"
![image](https://user-images.githubusercontent.com/32454870/55105148-a5553d00-50aa-11e9-9b41-60d16ce88108.png)

**Comment by vdias38** [comment]
To resume, and with translations:

## Ao vivo / Live (illustration: celebration)
### Compartilhe acontecimentos em tempo real.
#### Aqui todos podem comemorar realizações, fazer perguntas ou sugestões de forma fácil. Acompanhe o que está acontecendo em sua organização no momento, há sempre alguém de aniversário ;-)

### Share events in real time.
#### Here everyone can celebrate achievements, ask questions or suggestions in an easy way. Track what is happening in your organization at the moment, there is always someone else's birthday ;-)

## Notícias / News (business plan)
### Seja informado com conteúdo direcionado.
#### Em -Notícias- publicamos informações relevantes sobre as atividades da empresa. Aqui você também pode comentar.

### Be informed with targeted content
#### In -News- we publish relevant information about the company's activities. Here you can also comment.

## Contatos / Contacts (online friends)
### Agenda de contatos
#### Compartilhe suas informações de contato e acesse aos contatos da sua empresa, seja de colegas ou setores específico. 

### Company directory
#### Share your own details and browse contact informations from colleagues or company departments.

**Comment by danconte72** [comment]
Diretório da empresa > Agenda de Contatos
