### ISSUE TITLE
Your app "infomobi" (Apple ID: XXX) has one or more issues - on deploy

### ISSUE THREAD

**Issue by danconte72** [meumobi/infomobi#360]
### What happened
On upload a version to app store connect 
>We identified one or more issues with a recent delivery for your app, "infomobi". Please correct the following issues, then upload again.

>"Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. [Learn more](https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."

### Why it happens
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/368#issuecomment-477826834 
> Parts of the OneSignal iOS SDK allow apps to use location targeting for push notifications (geofence notifications). Apple appears to now be scanning apps for any code that uses location services, even if the app doesn’t actually use it.

### How to fix
https://github.com/OneSignal/OneSignal-iOS-SDK/issues/368#issuecomment-477826834
> In the short term I would recommend putting an NSLocationAlwaysUsageDescription string in your Info.plist even if your app doesn’t actually use it. If your app calls setLocationShared(false) our SDK will not prompt the user for location permission.
>In the long term, splitting out the location functionality into a separate OneSignal/Location Cocoapod library should be a more permanent fix.

## Solution
Updated ios-permissions to be complaint with itunes check. To do this in multi-language should use [meumobi/cordova-plugin-ios-permissions](https://github.com/meumobi/cordova-plugin-ios-permissions)
to set permissions needed

**Comment by vdias38** [comment]
Seems you should call `setLocationShared(false)` to "[not prompt the user for location permission](https://github.com/OneSignal/OneSignal-iOS-SDK/issues/368#issuecomment-477826834)".
Did you check if mandatory to not prompt ?
