### ISSUE TITLE
images too small on item/details

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#361]
### Expected behaviour
[Original img](https://meumobi.com/uploads/items/7007249.png) should fit the wide screen

### Actual behaviour
![infoMobi__Improve_Employee_Experience_and_Skype](https://user-images.githubusercontent.com/9011612/55902635-e0d02b00-5bc3-11e9-9349-2212615767cc.png)

### Steps to reproduce
1.
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
### why it happens 
image original is smaller than the image requested to fit

### how to fix it
Add &scale=both imageflow parameter
so the image will scale until to fit the width asked 
- from
https://imageflow.meumobi.com/meumobi/items/7007249.png?width=2048&format=jpg
- to 
https://imageflow.meumobi.com/meumobi/items/7007249.png?width=2048&format=jpg&scale=both

**Comment by vdias38** [comment]
- why original img size is not used (369x239) ? instead of 62x40
- the [recommendation](https://github.com/meumobi/infomobi/wiki/Resizing-images#item-images-itemsimages) is to use 600x400, then should always be "smaller than the image requested to fit"

**Comment by danconte72** [comment]
I've tested, and this smaller size only happens when srcset is used. It's not a css problem with carrousel

![image](https://user-images.githubusercontent.com/32454870/60891633-0fe25100-a234-11e9-893f-88b16c3d03c4.png)
https://developer.mozilla.org/en-US/docs/Glossary/Intrinsic_Size 
https://www.w3.org/TR/css-sizing-3/#intrinsic-sizes
> the min-content size of a box in each axis is the size it would have if it was a float given an auto size in that axis (and no minimum or maximum size in that axis) and if its containing block was zero-sized in that axis. (In other words, the minimum size it has when sized as “shrink-to-fit”.)
[draft]

**Comment by danconte72** [comment]
Seen this example https://mdn.github.io/learning-area/html/multimedia-and-embedding/responsive-images/responsive.html refered on [Mozilla Responsive Images](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images). It looks like the default behavior

**Comment by danconte72** [comment]
updated [recommendation](https://github.com/meumobi/infomobi/wiki/Resizing-images#item-images-itemsimages) to 
> Recommended File to Upload:
min width: 1200px;
min height: 800px;
if width>1200:
min-height = width/1.5

**Comment by vdias38** [comment]
### comments-list

```html
<img class="image-fit" imageviewer="" ng-reflect-src="" src="https://imageflow.meumobi.com/firebase/P4WF?width=1028&amp;scale=both&amp;format=jpg" srcset="https://imageflow.meumobi.com/firebase/P4WF?width=2048&amp;format=jpg 2048w,https://imageflow.meumobi.com/firebase/P4WF?width=1024&amp;format=jpg 1024w,https://imageflow.meumobi.com/firebase/P4WF?width=600&amp;format=jpg 600w">
```

### items-list (1/2)

```html
<img src="https://imageflow.meumobi.com/meumobi/items/1200x800_7007504.jpg?width=1028&amp;scale=both&amp;format=jpg" srcset="https://imageflow.meumobi.com/meumobi/items/1200x800_7007504.jpg?width=2048&amp;format=jpg 2048w,https://imageflow.meumobi.com/meumobi/items/1200x800_7007504.jpg?width=1024&amp;format=jpg 1024w,https://imageflow.meumobi.com/meumobi/items/1200x800_7007504.jpg?width=600&amp;format=jpg 600w">
```
### items-list (2/2)

```html
<img src="https://imageflow.meumobi.com/meumobi/items/1200x800_7007469.jpg?width=1024&amp;scale=both&amp;format=jpg" srcset="https://imageflow.meumobi.com/meumobi/items/1200x800_7007469.jpg?width=2048&amp;format=jpg 2048w,https://imageflow.meumobi.com/meumobi/items/1200x800_7007469.jpg?width=1024&amp;format=jpg 1024w,https://imageflow.meumobi.com/meumobi/items/1200x800_7007469.jpg?width=600&amp;format=jpg 600w">
```

### item-detail (1/2)

```html
<img imageviewer="" ng-reflect-src="" src="https://imageflow.meumobi.com/meumobi/items/7007504.jpg?width=1028&amp;scale=both&amp;format=jpg" srcset="https://imageflow.meumobi.com/meumobi/items/7007504.jpg?width=2048&amp;format=jpg 2048w,https://imageflow.meumobi.com/meumobi/items/7007504.jpg?width=1024&amp;format=jpg 1024w,https://imageflow.meumobi.com/meumobi/items/7007504.jpg?width=600&amp;format=jpg 600w">
```
### item-detail (2/2)

```html
<img imageviewer="" ng-reflect-src="" src="https://imageflow.meumobi.com/meumobi/items/7007469.jpg?width=1024&amp;scale=both&amp;format=jpg" srcset="https://imageflow.meumobi.com/meumobi/items/7007469.jpg?width=2048&amp;scale=both&amp;format=jpg 2048w,https://imageflow.meumobi.com/meumobi/items/7007469.jpg?width=1024&amp;scale=both&amp;format=jpg 1024w,https://imageflow.meumobi.com/meumobi/items/7007469.jpg?width=600&amp;scale=both&amp;format=jpg 600w">
```

||comments-list|items-list (1/2)|items-list (2/2)|item-detail (1/2)|item-detail (2/2)|
|---|---|---|---|---|---|
|Chrome inspector - iPad, 768x1024|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953551-492ec580-a2f5-11e9-8380-8ffe5faead08.png) firebase/P4WF?width=2048 loaded (688 x 517 intrinsic 2048 x 1539)|NA: 3 columns per row||![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953631-6ebbcf00-a2f5-11e9-93a9-a9c5aa8333f3.png) 7007504.jpg?width=2048 loaded (249 x 167 intrinsic 665 x 445)||
|Chrome inspector - iPhone 6/7/8, 375x667|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953361-efc69680-a2f4-11e9-8220-0e9cc8a85119.png) firebase/P4WF?width=600 loaded (295 x 222 intrinsic 600 x 451)|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953122-729b2180-a2f4-11e9-9589-1a52578b4fd2.png)1200x800_7007504.jpg?width=600 loaded (341 x 228 intrinsic 600x402)||![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953245-b55cf980-a2f4-11e9-8814-735bfb26b55f.png) 7007504.jpg?width=600 loaded (333 x 223 intrinsic 600 x 402)||
|Chrome inspector - Galaxy S5, 360x640|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953821-cb1eee80-a2f5-11e9-98f9-f02967c854c0.png) firebase/P4WF?width=1024 loaded (280 x 210 intrinsic 1024 x 769)|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953873-ebe74400-a2f5-11e9-85f0-e61c0faae17b.png) 1200x800_7007504.jpg?width=1024 loaded (330 x 221 intrinsic 665 x 445)|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/61001103-d22a1900-a356-11e9-8b6d-df7ec77a5d4e.png) 1200x800_7007469.jpg?width=1024 loaded (330 x 165 intrinsic 318 x 159)|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/60953925-04eff500-a2f6-11e9-9640-0087e94a4430.png) 7007504.jpg?width=1024 loaded (234 x 156 intrinsic 665 x 445)|![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/61001638-e6bae100-a357-11e9-8017-033d1531a603.png) 1200x800_7007469.jpg?width=1024 loaded (112 x 56 intrinsic 318 x 159)|
|Native device - SM-J320M 720x1280 (xhdpi) smallest width 360dp||![DevTools_-_file____android_asset_www_index_html__home_nav_n6_items](https://user-images.githubusercontent.com/9011612/61003118-11f2ff80-a35b-11e9-9e21-70d10ece2f8a.png) 1200x800_7007504.jpg?width=600 loaded (330 x 221 intrinsic 600 x 402)|![DevTools_-_file____android_asset_www_index_html__home_nav_n6_items](https://user-images.githubusercontent.com/9011612/61003039-db1ce980-a35a-11e9-853b-6ab4de8f8ba4.png) 1200x800_7007469.jpg?width=600 loaded (330 x 165 intrinsic 318 x 159)|![DevTools_-_web_infomobi_app_index_html_utm_source_home_screen__home_nav_n5_live](https://user-images.githubusercontent.com/9011612/60967486-b13fd480-a312-11e9-9946-f64c93c7c76e.png) 7007504.jpg?width=600 loaded (318 x 213 intrinsic 600 x 402)|![DevTools_-_file____android_asset_www_index_html__home_nav_n6_items](https://user-images.githubusercontent.com/9011612/61003307-862da300-a35b-11e9-8945-94471a79eba6.png) 1200x800_7007469.jpg?width=600 loaded (191 x 95 intrinsic 318 x 159)|

firebase/P4WF?width=2048 loaded (688 x 517 intrinsic 2048 x 1539) means:
- the img loaded by the browser according to responsive srcset: firebase/P4WF?width=2048
- render dimension (layout width and height in the browser): 688 x 517
- original dimension (original width and height): 2048 x 1539

On items-list there's a css selector
```css
ion-card img {
  width: 100%
}
```
If I remove it the img size displayed on Chrome inspector - Galaxy S5 on items-list 2/2 drop to 112 x 56, same as item-detail.

## Why it happens
Images are selected by browser according to width specified on [srcset](https://cloudfour.com/thinks/responsive-images-101-part-4-srcset-width-descriptors/) by the "w" descriptor. In following case, `1200x800_7007469.jpg?width=1024 loaded` it tells the browser that the image’s width is 1024px, but it's not... Our img is 318px width. 

If we set the correct width of img as w descriptor it fix the issue.

I didn't find the resize ratio applied on w descriptor to compute result size img
- if 1024w and 318 width then result width is 112 => a resize ratio of 2.84 (318/112)
- if 636w (I tested locally) and 318 width then result width is 180 => a resize ratio of 1.76 (318/180)

## How to fix it
We should provide images larger enough to fit all targeted screens AND a use correct width as w descriptor to prevent bad resize by browser.

[Imageflow](https://imageresizing.net/docs/basics) by default not enlarge image, it means that `1200x800_7007469.jpg?width=1024` will have 1024 width if original img has a 1024+ width, else it maintains original width. To enlarge img to fit required width we should use `scale=both` query param.
Then `imgServerSrcsettify` pipe should return `${prefix}?width=${width}&scale=both&format=jpg ${width}w`

## How to test
- on previous table resized imgs on item-detail should fit be resized as expected on width param of url and fit wide screen (expect margins).
