### ISSUE TITLE
poll.picture is missing

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#364]
### Expected behaviour
Tell us what should happen

### Actual behaviour
polls.picture is missing on news screen. The img url is setted on items feed.

![infoMobi__Improve_Employee_Experience](https://user-images.githubusercontent.com/9011612/56927913-40d43600-6acd-11e9-93d2-098d94d8ebe9.png)

### Steps to reproduce
1. 
2.
3.

### Expected responses
- Why it happens
- How to fix it
- How to test

**Comment by danconte72** [comment]
### why it happens
only show when picture when the api response item with thumbnails
- SHOWS IMAGE
```
...
images: [{id: "7007402", model: "Items", foreign_key: "5cefe15b9abba51b347029e2",…}]
..
options: ["Muito boa", "Boa", "Regular", "Ruim"]
..
thumbnails: [{width: "80", height: "60", url: "https://meumobi.com/uploads/items/80x60_7007402.jpg"},…]
0: {width: "80", height: "60", url: "https://meumobi.com/uploads/items/80x60_7007402.jpg"}
1: {width: "80", height: "80", url: "https://meumobi.com/uploads/items/80x80_7007402.jpg"}
2: {width: "139", height: "139", url: "https://meumobi.com/uploads/items/139x139_7007402.jpg"}
3: {width: "314", height: "220", url: "https://meumobi.com/uploads/items/314x220_7007402.jpg"}
4: {width: "1200", height: "800", url: "https://meumobi.com/uploads/items/1200x800_7007402.jpg"}
title: "Como avaliam a apresentação do infomobi?"
type: "polls"
...
```
- DOES NOT SHOW IMAGE
```
...
images: [{id: "7007296", model: "Items", foreign_key: "5cc75b5b9a645db6477b23c6",…}]
...
options: ["Muito boa", "Boa", "Regular", "Ruim"]
...
thumbnails: []
title: "Como voce avalia a qualidade da recepção ?"
type: "polls"
...
```

Articles and Polls use Thumbnail url to show
```html
<img *ngIf="item.thumbnailUrl" [src]="item.thumbnailUrl | imgServerUrly" [srcset]="item.thumbnailUrl | imgServerSrcsettify" />
```
### how to fix
I've checked on http://comunique-se.meumobilesite.com/categories and the image was missing
I've reuploaded the image and it worked

![image](https://user-images.githubusercontent.com/32454870/60836587-61d79800-a19c-11e9-81b9-0f3e328fd5d7.png)

**Comment by vdias38** [comment]
means the issue is from sitebuilder: item.thumbnail is empty despite item.images > 0. This was an issue but should be fixed on Feb on Elefante, see meumobi/sitebuilder#633, current issue has been observed on april, why it happens ?

**Comment by danconte72** [comment]
On trello card `migrate ELEFANTE to vps-2 (guepardo)`has more information.
But the original image was lost on backup image script fail on migration.
This error should not be occur anymore.
