### ISSUE TITLE
add my files link on header to list downloaded files

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#367]
### Expected behaviour
List files downloaded
Add link to "my files" on header w/ download [ionic icon](https://ionicframework.com/docs/v3/ionicons/)

**Comment by danconte72** [comment]
- Icon available only on Native app
- new files page
     1. get files array using mmb-media-provider->getFilesFromStorage;
     2. files are listed on download order;
     3. pass files array media-list component;
     4. reorder array by file.name;

**Comment by vdias38** [comment]
- listed on download order means by date of download ? if true it's fine, no need to reorder by file.name
- "Icon available only on Native app" you mean display link only on Native App, right ? if true, ok. how do you pretend to apply this rule ? do we have a pipe, ionic provide, etc. ??

**Comment by danconte72** [comment]
>listed on download order means by date of download ? if true it's fine, no need to reorder by file.name

yes
> "Icon available only on Native app" you mean display link only on Native App, right ? 

yes
> how do you pretend to apply this rule ?

we've been using 'this.platform.is('cordova')'
