### ISSUE TITLE
login form disappear on top when focus on input on mobile

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#41]
Same issue occured on ion-ams-report meumobi/ion-ams-report#65

|login form when focus input on ion-employee|login form when focus input on ams-report|
|---|---|
|![screenshot_2017-12-29-08-15-06](https://user-images.githubusercontent.com/9011612/34437949-b505751e-ec9a-11e7-8646-07ff26fffe15.png)|![screenshot_2017-12-29-08-18-16](https://user-images.githubusercontent.com/9011612/34437981-0451eb16-ec9b-11e7-80bb-36240f95655f.png)|

**Comment by danconte72** [comment]
Fix has been found on #10984  issue thread on [ionic-team/ionic/issues]( https://github.com/ionic-team/ionic/issues/)
