### ISSUE TITLE
add tv channel page: listing all video media (mpeg and youtube) from site

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#57]

**Comment by vdias38** [comment]
from channel id, list youtube videos
https://devdactic.com/ionic-youtube-rest-api/

**Comment by vdias38** [comment]
The idea is to find a generic way to serve youtube channel and m3u8 stream. Site should use one or another, don't both solutions.

**Comment by danconte72** [comment]
To enable youtube api you must to access https://console.developers.google.com/apis/library/youtube.googleapis.com?project=ion-employee

**Comment by danconte72** [comment]
The tutorials demands a cordova-plugin to play yt videos.
should find a pwa compatible player or embed videos on iframes?

**Comment by vdias38** [comment]
I you'd like another example running for web browser I recommend [onsen ui demo](https://github.com/frandiox/OnsenUI-YouTube)

posts about yt and onsen
- https://medium.com/the-web-tub/make-a-youtube-app-with-angularjs-and-onsen-ui-c836e7e046e0
- https://onsen.io/blog/tags/youtube.html

**Comment by vdias38** [comment]
Simon Grimm already provide a PWA fallback w/ `window.open` on `src/pages/playlist/playlist.ts`
```
...
    if (this.plt.is('cordova')) {
      this.youtube.openVideo(video.snippet.resourceId.videoId);
    } else {
      window.open('https://www.youtube.com/watch?v=' + video.snippet.resourceId.videoId);
    }
```

onsen demo use [youtube iframe API](https://developers.google.com/youtube/iframe_api_reference) for both web and app, and seems to play well, so I recommend to explore this way to play videos without the need of a cordova plugin integration (increase dependency and risk of bug).
The way onsen integrate the iframe api is not clean (insert script on `app.run`) but there are plenty of integration examples (like [this](https://www.youtube.com/watch?v=HgJ33r0qWf8), [this](https://time2hack.com/2017/11/easiest-way-to-integrate-youtube-iframe-api-in-angular-and-react/) or [ngx-embed-video lib](https://www.npmjs.com/package/ngx-embed-video)) of ionic and youtube iframe on web.

**Comment by danconte72** [comment]
### Dependencies
  - API key to access [yt api ](https://developers.google.com/youtube/v3/)
  - [CordovaYoutubeVideoPlayer](https://github.com/ihadeed/CordovaYoutubeVideoPlayer)
    - iOS and Android compatible recently updated, couldn’t find a pwa fallback 
### Project
- Page to list all playlist/channel videos with description
  - Select to choose playlist
  - Open video directly, Using one of some available players listed [here](https://github.com/meumobi/ion-employee/issues/57#issuecomment-444702045) 
### Service
- Fetch channel playlists 
- Fetch playlist videos
- Fetch [latest channel videos](https://stackoverflow.com/questions/18953499/youtube-api-to-fetch-all-videos-on-a-channel)
## Ideas
For me playlists navigation are unusual, I suggest fetch the latest videos from an entire channel as the default playlist. So in this way users will see videos list when open the Page, but they can change playlists
![img_3872](https://user-images.githubusercontent.com/32454870/49580493-2e970700-f936-11e8-9b94-e88ed2d7932e.jpg)

**Comment by danconte72** [comment]
I've Responsive yb iframe [embed](https://avexdesigns.com/responsive-youtube-embed/) to make video frame responsive
