### ISSUE TITLE
add on tv channel a m3u8 stream as live stream

### ISSUE THREAD

**Issue by vdias38** [meumobi/infomobi#58]
Use a default image with play icon. If user click it plays the m3u8 stream
In order to play it we can use [html video tag](https://stackoverflow.com/questions/19782389/playing-m3u8-files-with-html-video-tag)

If not well supported on iOS or Android there's a fallback solution through the [cordova-plugin-streaming-media](https://github.com/nchutchind/cordova-plugin-streaming-media) or

Cordova Streaming media
https://github.com/nchutchind/cordova-plugin-streaming-media/issues/80
https://github.com/nchutchind/cordova-plugin-streaming-media/issues/77

**Comment by vdias38** [comment]
- [Example of stream](https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/)
- [online streaming video player](http://player.kaltura.com/modules/KalturaSupport/tests/HLSPlaybackTester.html)

# What is HLS?

> HTTP Live Streaming (HLS) is an HTTP-based media streaming communications protocol implemented by Apple Inc. as part of its QuickTime, Safari, OS X, and iOS software. It works by breaking the overall stream into a sequence of small HTTP-based file downloads, each download loading one short chunk of an overall potentially unbounded transport stream.

# What is M3U8?

> M3U8 is a computer file format that contains multimedia playlists. A m3u8 file specifies the locations of one or more media files, rather than the video itself. Therefore, a HLS player is required to download and play the actual video files.

**Comment by vdias38** [comment]
Error in cordova-plugin-media while playing m3u8 file
> use of the Cordova device plugin to identify the device platform and invoke Cordova media plugin for iOS and exoplayer plugin for Android.
[Source](https://stackoverflow.com/a/46592277/4982169)

[HTML5 Video](https://www.html5rocks.com/en/tutorials/video/basics/)
[HLS Client](https://github.com/video-dev/hls.js)
[Supported players](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)

**Comment by vdias38** [comment]
[Ionic 3 - inline video opens in fullscreen in native player on iOS 10](https://stackoverflow.com/questions/45568964/ionic-3-inline-video-opens-in-fullscreen-in-native-player-on-ios-10)
[insert a list of videos in ionic 2?](https://stackoverflow.com/questions/44130736/how-can-i-insert-a-list-of-videos-in-ionic-2)

**Comment by danconte72** [comment]
Should use Video (youtube icon) to show youtube channel;
Should use TV (tv icon) to show m3u8 streaming;
m3u8 url must be set on settings;

**Comment by danconte72** [comment]
- create streaming page
- add m3u8 url on settings
should test html video tag on native (android/ios) and web, 
if not must to use a plugin to do this https://ionicframework.com/docs/native/streaming-media

**Comment by danconte72** [comment]
m3u8 on video tag is not supported on chrome desktop https://caniuse.com/#search=m3u8 
I've tested and It worked on:
- iOS safari;
- Mac safari;
- Android chrome;
- Android native;
- iOS native (through emulator);

**Comment by danconte72** [comment]
a m3u8 for chrome fallback is possible using this [hls.js](https://github.com/video-dev/hls.js/)
[source](https://stackoverflow.com/questions/23388135/how-to-play-html5-video-play-m3u8-on-mobile-and-desktop) [demo](https://video-dev.github.io/hls.js/demo/)

If we use this lib we don't need a plugin

**Comment by danconte72** [comment]
looks like a js lib well tested, https://github.com/video-dev/hls.js/#they-use-hlsjs-in-production 
im looking for npm package with this lib

**Comment by vdias38** [comment]
Some popular libs to handle videos (incl. hls):
- [videogular](https://github.com/videogular/videogular2)
include hls.js, but you [should declare it](https://stackoverflow.com/a/54471886/4982169)
- [video.js](https://github.com/videojs/video.js)
  - [tutorial: Angular 6 com video.js](https://medium.com/aprendajs/angular-6-com-video-js-3b1ac15a26ee)
