### ISSUE TITLE
Add CloudFunction to post “Today’s anniversaries

### ISSUE THREAD

**Issue by danconte72** [meumobi/infomobi#90]
Anniversaries CF:
  - Get the current day;
  - Get Contacts who have birthday on current day;
  - Create the anniversaries comment, with the contacts;

Trigger:
 - URL trigger to test CF;
 - Study how to use a cron on Firebase CF:
   - official [way](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html);

**Comment by vdias38** [comment]
The official way could be good to start, for a future release [this post](https://angularfirebase.com/lessons/scheduled-tasks-and-cron-jobs-with-firebase/) provides a more robust solution managing jobs and queueManager.
