### ISSUE TITLE
Replace Hydration by own App Trigger Update

### ISSUE THREAD

**Issue by elbidone** [meumobi/infomobi#94]
# Managing Updates
## Objective
The purpose of this issue is to provide a new way to update in-house App that lets the user know when there is an update, so when the user press the update button the app calls itms-services to download and install the latest version.
This objective could be divided in two parts:
- check if exists a **new version of App**. Not build number, as done by Hydration, but version number contained on config.xml
- update app. Hydration only updates the www/, we should be able to update the whole app.

## Update iOS App
With iOS, to install the application, we only need to provide the iTunes link to our plist application (something like this: itms-services://?action=download-manifest&url=http://url.to.plist) and open it with the InAppBrowser plugin.. Theyʼll get a simple dialog asking them if they want to proceed with install. An example of itms-services url:
itms-services://?action=download-manifest&url=https%3A%2F%2Fbuild.phonegap.com%2Fapps%2F1420565%2Fplist%3Fqr_key%3D46yd1cybHTCGnXKC2ymd

We can also send push for update
Send Push with url=https://build.phonegap.com/apps/1420565/install as additional data

As explained on [Provision iOS IPA App for In-House Enterprise Distribution]
> In order to be able to install the IPA file over the Internet, navigate to the html file using HTTPS. This is mandatory since iOS 7.1.
[Provision iOS IPA App for In-House Enterprise Distribution]: http://johannesluderschmidt.de/provision-ios-ipa-app-for-in-house-enterprise-distribution/2993/
[Distribute iOS Apps to users]: https://www.apple.com/lae/business/accelerator/deploy/app-distribution.html

## Update Android App
With Android we cannot create a link to APK file. It doesn’t work. We need to download the APK (using FileTransfer plugin) and open the file using webintent plugin.
Below the code to [Upgrade Cordova-Android apps ]. The code downloads the apk from a remote server to the download folder in the sdcard and then triggers the install. Other code resource is available on [Phonegap Android app trigger update].
```javascript
var fileTransfer = new FileTransfer();
fileTransfer.download(encodeURI(androidUrl), 
    "cdvfile://localhost/temporary/app.apk",
    function (entry) {
        window.plugins.webintent.startActivity({
            action: window.plugins.webintent.ACTION_VIEW,
            url: entry.toURL(),
            type: 'application/vnd.android.package-archive'
        }, function () {
        }, function () {
            alert('Failed to open URL via Android Intent.');
            console.log("Failed to open URL via Android Intent. URL: " + entry.fullPath);
        });
    }, function (error) {
        console.log("download error source " + error.source);
        console.log("download error target " + error.target);
        console.log("upload error code" + error.code);
    }, true);
```
[Upgrade Cordova-Android apps ]: http://gonzalo123.com/2014/07/28/upgrading-android-apps-outside-google-play-store-with-angularjs/
[Phonegap Android app trigger update]: http://stackoverflow.com/questions/15880866/phonegap-android-app-trigger-update-programmatically

# Check App version
## PhoneGap Build Read API  
The [PhoneGap Build Read API] allows to Get App details by Id.
Get /api/v1/apps/:id

```
json
{
    "id": 843971,
    "title": "InfoBox",
    "package": "com.meumobi.infobox",
    "version": "1.1.1",
    "description": "Mobile App for Internal Communication.",
    "icon": {
        "filename": "Icon-76@2x.png",
        "link": "/api/v1/apps/843971/icon"
    },
    "download": {
        "android": "/api/v1/apps/843971/android",
        "ios": "/api/v1/apps/843971/ios",
        "winphone": "/api/v1/apps/843971/winphone"
    },
...
}
```
## Authentication by Token
Pass your token as a parameter for any call that you make:
```
$ curl https://build.phonegap.com/api/v1/apps/843971?auth_token=ASTRINGTOKEN
```
## Get User's Token
Use basic authentication to post to /token with your request, and the token returns in the response
```
$ curl -u victor.dias@ipanemax.com -X POST -d "" https://build.phonegap.com/token
Enter host password for user 'victor.dias@ipanemax.com':
{"token":"dVp5pEQYSCPxXaUprtPP"}
```

## Check New Version
during Dev we can add a button 
On app.js call DeviceService.checkNewVersion().
If true then promptForUpdate()
checkNewVersion call build API with CONFIG.BUILD.USER_TOKEN, CONFIG.BUILD.URL, CONFIG.BUILD.APP_ID
If response.version != APP.version then promptForUpdate()

## Get Download Url

```
$ curl -H HEAD -i https://build.phonegap.com/api/v1/apps/1420565/android?auth_token=dVp5pEQYSCPxXaUprtPP
HTTP/1.1 302 Found
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8; charset=utf-8
Date: Mon, 01 Jun 2015 10:46:25 GMT
Location: http://s3.amazonaws.com/android.phonegap/slicehost-production/apps/87c618fa-e8c0-11e4-a4d4-92c8bcc89984/infoMobi-debug.apk
Server: Apache
Set-Cookie: remember_person_token=BAhbB1sGaQNd%2FgNJIiIkMmEkMTAkOXU0YXhFczhtWHRLZUJmdVRoQUppTwY6BkVU--1fc490939f6cba22c04562d5bacd2bc86c776a5c; path=/; expires=Tue, 02 Jun 2015 12:29:57 -0000; HttpOnly; secure
Status: 302 Found
```

## Show Progress download, Android
...

# Call REST PhoneGap Build API
on API Service (meumobi-api.js) add on app 
```js
Build: (function() {
		var path = '/api/v1/apps/' + CONFIG.BUILD.APP_ID;
		return {
			query: function(success, error) {
				build.get(path, success, error);
			}
		}
	})(),
```
# Build Release for in-house Distribution
If distribution is in-house, on app.js call DeviceService.checkNewVersion().
Use gulp-template and CONFIG.distribution = inHouse | appStore

# Update Config Environment
add on /environments/[ENV].json APP.BUILD
- url
- appId
- userToken

# Prompt for Update
like /welcome or /otp create a /update page with click to "Update App"
The Update App button should call updateAndroid or updateIOS.

## Send Push with custom URL scheme
we can send push with url to open infomobi://upgrade
https://github.com/EddyVerbruggen/Custom-URL-scheme

# TODO
- when to call checkNewVersion
- what UX: new page, Action Sheet, overlay  ?

If a new version is available 2 methods are available:
- for iOS loading an ipa file update the App
http://stackoverflow.com/questions/15880866/phonegap-android-app-trigger-update-programmatically

[PhoneGap Build Read API]: http://docs.build.phonegap.com/en_US/developer_api_read.md.html

**Comment by t4deu** [comment]
Very interesting, how the IOS update will work?
